import { request } from "../../../core/api/transport";
import type { AdminGroup, AdminUser, IdentityGroup, IdentityHistory, IdentityProfile, IdentityRoles, IdentityUser, PermissionMetadata, RbacAssignment, RbacRole, RbacRoles } from "../../../core/api/contracts";

export const identityClient = {
  identityMe: () => request<IdentityProfile>("/api/identity/me"),
  identityPermissions: () => request<PermissionMetadata[]>("/api/identity/permissions"),
  identityRoles: () => request<IdentityRoles>("/api/identity/roles"),
  identityHistory: (limit = 200) => request<IdentityHistory[]>(`/api/identity/history?limit=${limit}`),
  identityUsers: (params: { search?: string; role?: string; status?: string; include_system?: boolean } = {}) => { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== "" && value !== false) query.set(key, String(value)); }); return request<IdentityUser[]>(`/api/identity/users${query.size ? `?${query}` : ""}`); },
  identityUser: (username: string) => request<IdentityUser>(`/api/identity/users/${encodeURIComponent(username)}`),
  createIdentityUser: (payload: Record<string, unknown>) => request<IdentityUser>("/api/identity/users", { method: "POST", body: JSON.stringify(payload) }),
  updateIdentityUser: (username: string, payload: Record<string, unknown>) => request<IdentityUser>(`/api/identity/users/${encodeURIComponent(username)}`, { method: "PATCH", body: JSON.stringify(payload) }),
  deleteIdentityUser: (username: string, remove_home: boolean) => request(`/api/identity/users/${encodeURIComponent(username)}`, { method: "DELETE", body: JSON.stringify({ confirm: true, remove_home }) }),
  lockIdentityUser: (username: string, locked: boolean) => request(`/api/identity/users/${encodeURIComponent(username)}/${locked ? "lock" : "unlock"}`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  changeIdentityUserPassword: (username: string, new_password: string, force_change: boolean) => request(`/api/identity/users/${encodeURIComponent(username)}/password`, { method: "POST", body: JSON.stringify({ new_password, force_change, confirm: true }) }),
  setIdentityUserQuota: (username: string, soft_mb: number, hard_mb: number | null, mountpoint: string | null) => request(`/api/identity/users/${encodeURIComponent(username)}/quota`, { method: "POST", body: JSON.stringify({ soft_mb, hard_mb, mountpoint, confirm: true }) }),
  saveIdentityUserPolicy: (username: string, policy: { role: RbacRole; allow: string[]; deny: string[] }) => request<IdentityUser>(`/api/identity/users/${encodeURIComponent(username)}/policy`, { method: "PUT", body: JSON.stringify({ ...policy, confirm: true }) }),
  identityEffectivePermissions: (username: string) => request<IdentityProfile>(`/api/identity/users/${encodeURIComponent(username)}/effective-permissions`),
  identityGroups: (params: { search?: string; include_system?: boolean } = {}) => { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== "" && value !== false) query.set(key, String(value)); }); return request<IdentityGroup[]>(`/api/identity/groups${query.size ? `?${query}` : ""}`); },
  createIdentityGroup: (payload: Record<string, unknown>) => request<IdentityGroup>("/api/identity/groups", { method: "POST", body: JSON.stringify(payload) }),
  renameIdentityGroup: (groupname: string, new_name: string) => request<IdentityGroup>(`/api/identity/groups/${encodeURIComponent(groupname)}`, { method: "PATCH", body: JSON.stringify({ new_name, confirm: true }) }),
  deleteIdentityGroup: (groupname: string) => request(`/api/identity/groups/${encodeURIComponent(groupname)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  setIdentityGroupMember: (groupname: string, username: string, present: boolean) => request<IdentityGroup>(present ? `/api/identity/groups/${encodeURIComponent(groupname)}/members` : `/api/identity/groups/${encodeURIComponent(groupname)}/members/${encodeURIComponent(username)}`, { method: present ? "POST" : "DELETE", body: JSON.stringify({ username, confirm: true }) }),
  saveIdentityGroupPolicy: (groupname: string, policy: { allow: string[]; deny: string[] }) => request<IdentityGroup>(`/api/identity/groups/${encodeURIComponent(groupname)}/policy`, { method: "PUT", body: JSON.stringify({ ...policy, confirm: true }) }),
  adminUsers: () => request<AdminUser[]>("/api/admin/users"),
  createUser: (payload: Record<string, unknown>) => request<AdminUser>("/api/admin/users", { method: "POST", body: JSON.stringify(payload) }),
  patchUser: (username: string, payload: Record<string, unknown>) => request<AdminUser>(`/api/admin/users/${encodeURIComponent(username)}`, { method: "PATCH", body: JSON.stringify(payload) }),
  deleteUser: (username: string) => request(`/api/admin/users/${encodeURIComponent(username)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  lockUser: (username: string) => request(`/api/admin/users/${encodeURIComponent(username)}/lock`, { method: "POST", body: "{}" }),
  unlockUser: (username: string) => request(`/api/admin/users/${encodeURIComponent(username)}/unlock`, { method: "POST", body: "{}" }),
  changeUserPassword: (username: string, payload: Record<string, unknown>) => request(`/api/admin/users/${encodeURIComponent(username)}/change-password`, { method: "POST", body: JSON.stringify(payload) }),
  setUserQuota: (username: string, payload: Record<string, unknown>) => request(`/api/admin/users/${encodeURIComponent(username)}/quota`, { method: "POST", body: JSON.stringify(payload) }),
  adminGroups: () => request<AdminGroup[]>("/api/admin/groups"),
  createGroup: (payload: Record<string, unknown>) => request("/api/admin/groups", { method: "POST", body: JSON.stringify(payload) }),
  deleteGroup: (groupname: string) => request(`/api/admin/groups/${encodeURIComponent(groupname)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  addGroupMember: (groupname: string, payload: Record<string, unknown>) => request(`/api/admin/groups/${encodeURIComponent(groupname)}/members`, { method: "POST", body: JSON.stringify(payload) }),
  removeGroupMember: (groupname: string, username: string) => request(`/api/admin/groups/${encodeURIComponent(groupname)}/members/${encodeURIComponent(username)}`, { method: "DELETE", body: "{}" }),
  chown: (payload: Record<string, unknown>) => request("/api/admin/files/ownership", { method: "POST", body: JSON.stringify(payload) }),
  chmod: (path: string, mode: string) => request("/api/files/chmod", { method: "POST", body: JSON.stringify({ path, mode }) }),
  rbacMe: () => request<{ role: RbacRole; permissions: string[]; role_source: string; is_admin: boolean }>("/api/rbac/me"),
  rbacRoles: () => request<RbacRoles>("/api/rbac/roles"),
  rbacAssignments: () => request<RbacAssignment[]>("/api/rbac/assignments"),
  saveRbacAssignment: (assignment: Pick<RbacAssignment, "username" | "role" | "allow" | "deny">) => request<RbacAssignment>(`/api/rbac/assignments/${encodeURIComponent(assignment.username)}`, { method: "PUT", body: JSON.stringify(assignment) })
} as const;
