import type { UserPreferences } from "../api";

export const defaultUserPreferences: UserPreferences = {
  language: "pl-PL",
  theme: "system",
  startup_windows: "last",
  wallpaper: "",
  accent_color: "blue",
  wallpaper_fit: "cover",
  taskbar_alignment: "center",
  pinned_apps: ["files", "transfers", "monitor", "settings"],
  pinned_modules: [],
  start_pinned_apps: ["files", "transfers", "monitor", "settings"],
  desktop_shortcut_apps: ["files", "transfers", "monitor", "settings"],
  show_desktop_shortcuts: true,
  desktop_shortcut_size: "medium",
  show_welcome_widget: true,
  show_notifications: true,
  show_transfer_indicator: true,
  window_transparency: true,
  animations_enabled: true,
  clock_show_seconds: false,
  date_format: "short",
  time_format: "24",
  interface_scale: 100,
  interface_font: "system",
  larger_text: false,
  high_contrast: false,
  reduced_motion: false,
  strong_active_borders: false,
  always_show_focus: false,
  file_default_view: "list",
  file_compact_rows: false,
  file_show_hidden: false,
  file_confirm_delete: true,
  file_confirm_overwrite: true,
  file_page_size: 50,
  file_default_sort: "name",
  file_sort_direction: "asc",
  file_remember_last_path: true,
  transfer_success_notifications: true,
  transfer_error_notifications: true,
  transfer_open_failed_details: false,
  transfer_remember_filter: true,
  notification_transfer: true,
  notification_errors: true,
  notification_admin: true,
  notification_auto_hide: true,
  notification_limit: 5,
  first_day_of_week: "locale",
  widgets_enabled: true,
  desktop_widgets: [
    { id: "cpu", visible: true, x: 0, y: 0, width: 3, height: 2 },
    { id: "ram", visible: true, x: 3, y: 0, width: 3, height: 2 },
    { id: "disks", visible: true, x: 6, y: 0, width: 4, height: 2 },
    { id: "transfers", visible: true, x: 0, y: 2, width: 4, height: 2 },
    { id: "services", visible: true, x: 4, y: 2, width: 3, height: 2 },
    { id: "alerts", visible: true, x: 7, y: 2, width: 3, height: 2 },
  ],
};
