import { ListChecks, RefreshCw, RotateCcw, Square, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { ToastFn } from "../../app/types";
import { confirmDialog } from "../../components/DialogService";
import { Modal } from "../../components/Modal";
import { jobQueueClient, type Job, type JobSummary } from "./api/client";
import "../infrastructure-managers.css";

type Props={permissions:string[];language:string;toast:ToastFn};
export function JobQueueManagerApp({permissions,toast}:Props){
 const [summary,setSummary]=useState<JobSummary|null>(null),[jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<Job|null>(null),[logs,setLogs]=useState<Array<{created_at:number;level:string;message:string}>>([]),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{try{const [s,p]=await Promise.all([jobQueueClient.summary(),jobQueueClient.list()]);setSummary(s);setJobs(p.items);}catch(e){toast(e instanceof Error?e.message:"Job Queue error","error","admin","job-queue-manager");}finally{setLoading(false);}},[toast]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer);},[refresh]);
 async function details(job:Job){setSelected(job);try{setLogs((await jobQueueClient.logs(job.id)).items);}catch{setLogs([])}}
 async function action(job:Job,kind:"cancel"|"retry"){if(!(await confirmDialog(`${kind} ${job.name||job.type}?`,k=>k)))return;try{await jobQueueClient[kind](job.id);await refresh();}catch(e){toast(e instanceof Error?e.message:"Job action failed","error","admin","job-queue-manager")}}
 return <div className="infra-manager-app"><header className="infra-manager-header"><div className="infra-manager-title"><ListChecks/><div><h2>Job Queue Manager</h2><p>Central queue, progress, retries, cancellation and recovery.</p></div></div><div className="infra-manager-actions">{permissions.includes("jobs.manage")&&<button onClick={async()=>{if(await confirmDialog("Delete completed job history older than 30 days?",k=>k)){await jobQueueClient.cleanup();await refresh();}}}><Trash2/>Cleanup</button>}<button onClick={()=>void refresh()} disabled={loading}><RefreshCw className={loading?"spin":""}/>Refresh</button></div></header>
 <div className="infra-stat-grid"><div className="infra-stat"><strong>{summary?.running??0}</strong><small>Running</small></div><div className="infra-stat"><strong>{summary?.queued??0}</strong><small>Queued</small></div><div className="infra-stat"><strong>{summary?.failed??0}</strong><small>Failed</small></div><div className="infra-stat"><strong>{summary?.completed_today??0}</strong><small>Completed today</small></div><div className="infra-stat"><strong>{summary?.workers??0}</strong><small>Workers</small></div></div>
 <div className="infra-table-wrap"><table className="infra-table"><thead><tr><th>Job</th><th>Module</th><th>User</th><th>Priority</th><th>Status</th><th>Progress</th><th>Started</th><th>Actions</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><button type="button" onClick={()=>void details(j)}>{j.name||j.type}</button></td><td>{j.module}</td><td>{j.created_by}</td><td>{j.priority}</td><td>{j.status}</td><td>{j.progress??0}% {j.current_step}</td><td>{j.started_at?new Date(j.started_at*1000).toLocaleString():"—"}</td><td><div className="infra-row-actions">{j.cancellable&&permissions.includes("jobs.cancel")&&<button onClick={()=>void action(j,"cancel")}><Square/>Cancel</button>}{j.retryable&&["failed","cancelled","timed_out","blocked"].includes(j.status)&&permissions.includes("jobs.retry")&&<button onClick={()=>void action(j,"retry")}><RotateCcw/>Retry</button>}</div></td></tr>)}</tbody></table></div>
 {selected&&<Modal title={selected.name||selected.type} closeLabel="Close" onClose={()=>setSelected(null)}><div className="infra-log-list"><p><strong>{selected.status}</strong> · {selected.progress??0}% · {selected.correlation_id||selected.id}</p>{selected.error&&<div className="infra-manager-warning">{selected.error}</div>}{logs.map((entry,index)=><div className="infra-log-line" key={index}><strong>{new Date(entry.created_at*1000).toLocaleTimeString()} [{entry.level}]</strong> {entry.message}</div>)}</div></Modal>}</div>;
}
