import { Copy, Download, Filter, Plus, RefreshCw, Search, Server, ShieldCheck, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, type HostsManagerCapability, type HostsManagerDashboard, type HostsManagerEnrollmentToken, type HostsManagerGroup, type HostsManagerHost, type HostsManagerOperation, type ModuleStatus } from "../../../api";
import type { ToastFn, Translate } from "../../../app/types";
import { Modal } from "../../../components/Modal";
import { ModuleAppShell, ModuleHealthCard, type ModuleSection } from "../common/ModuleAppShell";

type Props = { permissions: string[]; t: Translate; toast: ToastFn };
const status: ModuleStatus = { installed: true, update_available: false, service_state: "not_applicable", service_enabled: false, services: {}, health: "healthy", health_message: "", last_action: "", last_action_status: "", last_error: "", metrics: {}, package_version: "1.0.0" };
const sections: ModuleSection[] = ["overview", "hosts", "groups", "enrollment", "discovery", "inventory", "credentials", "repositories", "power", "operations", "settings", "diagnostics", "backups"];

export function HostsManagerApp({ permissions, t, toast }: Props) {
  const [section, setSection] = useState<ModuleSection>("overview");
  const [dashboard, setDashboard] = useState<HostsManagerDashboard | null>(null);
  const [hosts, setHosts] = useState<HostsManagerHost[]>([]);
  const [groups, setGroups] = useState<HostsManagerGroup[]>([]);
  const [tokens, setTokens] = useState<HostsManagerEnrollmentToken[]>([]);
  const [operations, setOperations] = useState<HostsManagerOperation[]>([]);
  const [credentials, setCredentials] = useState<Array<Record<string, unknown>>>([]);
  const [repositories, setRepositories] = useState<Array<Record<string, unknown>>>([]);
  const [powerProfiles, setPowerProfiles] = useState<Array<Record<string, unknown>>>([]);
  const [diagnostics, setDiagnostics] = useState<Array<{ id: string; status: string; message: string }>>([]);
  const [backups, setBackups] = useState<Array<Record<string, unknown>>>([]);
  const [loading, setLoading] = useState(true);
  const can = (permission: string) => permissions.includes(permission);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const base = await Promise.all([api.hostsManagerDashboard(), api.hostsManagerHosts(), api.hostsManagerGroups()]);
      setDashboard(base[0]); setHosts(base[1]); setGroups(base[2]);
      if (permissions.includes("hosts-manager.hosts.manage")) setTokens(await api.hostsManagerEnrollmentTokens());
      if (permissions.includes("hosts-manager.audit.view")) setOperations(await api.hostsManagerOperations());
      if (permissions.includes("hosts-manager.credentials.view")) setCredentials(await api.hostsManagerCredentials() as unknown as Array<Record<string, unknown>>);
      if (permissions.includes("hosts-manager.repositories.view")) setRepositories(await api.hostsManagerRepositories());
      if (permissions.includes("hosts-manager.power.view")) setPowerProfiles(await api.hostsManagerPowerProfiles());
      if (permissions.includes("hosts-manager.configure")) setDiagnostics((await api.hostsManagerDiagnostics()).checks);
      if (permissions.includes("hosts-manager.backup")) setBackups(await api.hostsManagerBackups());
    } catch (error) {
      toast(error instanceof Error ? error.message : t("error.generic"), "error", "admin", "hosts-manager");
    } finally { setLoading(false); }
  }, [permissions, t, toast]);

  useEffect(() => { void refresh(); }, [refresh]);
  let content: React.ReactNode;
  if (section === "overview") content = <Dashboard value={dashboard} t={t} />;
  else if (section === "hosts") content = <Hosts items={hosts} groups={groups} permissions={permissions} t={t} toast={toast} refresh={refresh} />;
  else if (section === "groups") content = <Groups items={groups} canManage={can("hosts-manager.hosts.manage")} t={t} toast={toast} refresh={refresh} />;
  else if (section === "enrollment") content = <Enrollment items={tokens} groups={groups} canManage={can("hosts-manager.hosts.manage")} t={t} toast={toast} refresh={refresh} />;
  else if (section === "operations") content = <Operations items={operations} t={t} />;
  else if (section === "credentials") content = <Records title={t("hosts.credentials.title")} hint={t("hosts.credentials.hint")} items={credentials} t={t} />;
  else if (section === "repositories") content = <Records title={t("hosts.repositories.title")} hint={t("hosts.repositories.hint")} items={repositories} t={t} />;
  else if (section === "power") content = <Records title={t("hosts.power.title")} hint={t("hosts.power.hint")} items={powerProfiles} t={t} />;
  else if (section === "diagnostics") content = <Checks items={diagnostics} t={t} />;
  else if (section === "backups") content = <Records title={t("hosts.backups.title")} hint={t("hosts.backups.hint")} items={backups} t={t} />;
  else content = <Placeholder section={section} t={t} />;
  return <ModuleAppShell name={t("hosts.name")} status={status} healthMessage={t("hosts.subtitle")} section={section} sections={sections} t={t} onSection={setSection} actions={<button type="button" onClick={() => void refresh()}><RefreshCw className={loading ? "spin" : ""} />{t("action.refresh")}</button>}>{loading && !dashboard ? <div className="loading-state">{t("status.loading")}</div> : content}</ModuleAppShell>;
}

function Dashboard({ value, t }: { value: HostsManagerDashboard | null; t: Translate }) {
  if (!value) return null;
  const cards: Array<[string, number, "neutral" | "success" | "warning" | "danger"]> = [
    ["total", value.total, "neutral"], ["online", value.online, "success"], ["offline", value.offline, "danger"],
    ["unverified", value.unverified, "warning"], ["fingerprintErrors", value.fingerprint_errors, "danger"],
    ["pendingApproval", value.pending_approval, "warning"], ["ansibleAvailable", value.ansible_available, "success"], ["powerManaged", value.power_managed, "neutral"],
  ];
  return <><div className="module-health-grid ansible-dashboard">{cards.map(([key, count, tone]) => <ModuleHealthCard key={key} title={t(`hosts.dashboard.${key}`)} value={count} tone={tone} />)}</div><div className="ansible-panel"><h3>{t("hosts.operations.recent")}</h3><Operations items={value.recent_operations} t={t} /></div></>;
}

function Hosts({ items, groups, permissions, t, toast, refresh }: { items: HostsManagerHost[]; groups: HostsManagerGroup[]; permissions: string[]; t: Translate; toast: ToastFn; refresh: () => Promise<void> }) {
  const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [cards, setCards] = useState(false);
  const [editing, setEditing] = useState<HostsManagerHost | null | undefined>(); const [selected, setSelected] = useState<HostsManagerHost | null>(null);
  const filtered = useMemo(() => items.filter((item) => (!query || `${item.name} ${item.address} ${item.hostname} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())) && (!statusFilter || item.connection_status === statusFilter || item.fingerprint_status === statusFilter)), [items, query, statusFilter]);
  return <section className="ansible-panel"><header><div><h3>{t("hosts.list.title")}</h3><p>{t("hosts.list.hint")}</p></div>{permissions.includes("hosts-manager.hosts.manage") && <button className="button-primary" onClick={() => setEditing(null)}><Plus />{t("hosts.host.add")}</button>}</header><div className="module-section-toolbar"><label><Search /><input aria-label={t("action.search")} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("hosts.search.placeholder")} /></label><label><Filter /><select aria-label={t("hosts.filter.status")} value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">{t("hosts.filter.all")}</option><option value="online">{t("hosts.status.online")}</option><option value="offline">{t("hosts.status.offline")}</option><option value="unverified">{t("hosts.status.unverified")}</option><option value="changed">{t("hosts.status.changed")}</option></select></label><button type="button" onClick={() => setCards((value) => !value)}>{t(cards ? "hosts.view.list" : "hosts.view.cards")}</button></div>{cards ? <div className="card-grid">{filtered.map((item) => <article className="data-card" key={item.id}><header><Server /><strong>{item.name}</strong><Status value={item.connection_status} t={t} /></header><p>{item.address}:{item.port}</p><small>{item.environment || t("common.none")} · {item.location || t("common.none")}</small><button onClick={() => setSelected(item)}>{t("hosts.host.details")}</button></article>)}</div> : <div className="table-scroll"><table><thead><tr><th>{t("common.name")}</th><th>{t("hosts.host.address")}</th><th>{t("common.status")}</th><th>{t("hosts.host.fingerprint")}</th><th>{t("hosts.host.lastActivity")}</th><th>{t("column.actions")}</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><button className="link-button" onClick={() => setSelected(item)}>{item.name}</button></td><td>{item.address}:{item.port}</td><td><Status value={item.connection_status} t={t} /></td><td><Status value={item.fingerprint_status} t={t} /></td><td>{item.last_test_at ? new Date(item.last_test_at * 1000).toLocaleString() : t("common.none")}</td><td><div className="module-row-actions"><button onClick={() => setSelected(item)}>{t("hosts.host.details")}</button>{permissions.includes("hosts-manager.hosts.manage") && <button onClick={() => setEditing(item)}>{t("action.edit")}</button>}</div></td></tr>)}</tbody></table></div>}{!filtered.length && <div className="empty-state">{t("hosts.list.empty")}</div>}{editing !== undefined && <HostForm value={editing} groups={groups} t={t} toast={toast} onClose={() => setEditing(undefined)} onSaved={refresh} />}{selected && <HostDetails value={selected} permissions={permissions} t={t} toast={toast} onClose={() => setSelected(null)} refresh={refresh} />}</section>;
}

function HostForm({ value, groups, t, toast, onClose, onSaved }: { value: HostsManagerHost | null; groups: HostsManagerGroup[]; t: Translate; toast: ToastFn; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(value?.name || ""); const [address, setAddress] = useState(value?.address || ""); const [port, setPort] = useState(value?.port || 22);
  const [user, setUser] = useState(value?.ssh_user || "algen-ansible"); const [environment, setEnvironment] = useState(value?.environment || ""); const [location, setLocation] = useState(value?.location || ""); const [description, setDescription] = useState(value?.description || ""); const [tags, setTags] = useState(value?.tags.join(", ") || ""); const [groupIds, setGroupIds] = useState(value?.group_ids || []);
  async function save(event: React.FormEvent) { event.preventDefault(); try { await api.saveHostsManagerHost({ name, hostname: value?.hostname || "", fqdn: value?.fqdn || "", address, management_address: value?.management_address || "", port, connection_type: value?.connection_type || "ssh", ssh_user: user, credential_id: value?.credential_id || null, python_interpreter: value?.python_interpreter || "auto_silent", environment, location, description, tags: tags.split(",").map((item) => item.trim()).filter(Boolean), variables: value?.variables || {}, group_ids: groupIds, active: value?.active ?? true, approved: value?.approved ?? false, power_profile_id: null }, value?.id); toast(t("hosts.host.saved"), "ok"); await onSaved(); onClose(); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error"); } }
  return <Modal wide title={t(value ? "hosts.host.edit" : "hosts.host.add")} closeLabel={t("action.close")} onClose={onClose} footer={<><button onClick={onClose}>{t("action.cancel")}</button><button className="button-primary" type="submit" form="hosts-host-form">{t("action.save")}</button></>}><form id="hosts-host-form" className="module-form-grid" onSubmit={save}><label>{t("common.name")}<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>{t("hosts.host.address")}<input required value={address} onChange={(event) => setAddress(event.target.value)} /></label><label>{t("hosts.host.port")}<input type="number" min="1" max="65535" value={port} onChange={(event) => setPort(Number(event.target.value))} /></label><label>{t("hosts.host.user")}<input required value={user} onChange={(event) => setUser(event.target.value)} /></label><label>{t("hosts.host.environment")}<input value={environment} onChange={(event) => setEnvironment(event.target.value)} /></label><label>{t("hosts.host.location")}<input value={location} onChange={(event) => setLocation(event.target.value)} /></label><label className="wide">{t("hosts.host.description")}<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="wide">{t("hosts.host.tags")}<input value={tags} onChange={(event) => setTags(event.target.value)} /></label><fieldset className="wide"><legend>{t("hosts.groups.title")}</legend>{groups.map((group) => <label className="check" key={group.id}><input type="checkbox" checked={groupIds.includes(group.id)} onChange={(event) => setGroupIds((current) => event.target.checked ? [...current, group.id] : current.filter((id) => id !== group.id))} />{group.name}</label>)}</fieldset></form></Modal>;
}

function HostDetails({ value, permissions, t, toast, onClose, refresh }: { value: HostsManagerHost; permissions: string[]; t: Translate; toast: ToastFn; onClose: () => void; refresh: () => Promise<void> }) {
  const [capabilities, setCapabilities] = useState<HostsManagerCapability[]>([]); const [plan, setPlan] = useState<{ capability: HostsManagerCapability; value: Record<string, unknown> } | null>(null);
  useEffect(() => { void api.hostsManagerCapabilities(value.id).then(setCapabilities); }, [value.id]);
  async function review(capability: HostsManagerCapability) { try { setPlan({ capability, value: await api.hostsManagerActionPlan(value.id, capability.id) }); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error"); } }
  async function execute() { if (!plan) return; try { await api.executeHostsManagerAction(value.id, plan.capability.id, {}, value.name); toast(t("hosts.action.queued"), "ok"); setPlan(null); await refresh(); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error"); } }
  return <Modal wide title={value.name} closeLabel={t("action.close")} onClose={onClose}><div className="ansible-detail-grid"><section><h3>{t("hosts.details.summary")}</h3><dl><dt>{t("hosts.host.address")}</dt><dd>{value.address}:{value.port}</dd><dt>{t("hosts.host.environment")}</dt><dd>{value.environment || t("common.none")}</dd><dt>{t("hosts.host.location")}</dt><dd>{value.location || t("common.none")}</dd><dt>{t("hosts.host.fingerprint")}</dt><dd><Status value={value.fingerprint_status} t={t} /></dd><dt>{t("hosts.host.approval")}</dt><dd>{t(value.approved ? "common.yes" : "common.no")}</dd></dl></section><section><h3>{t("hosts.details.facts")}</h3><pre>{JSON.stringify(value.facts || {}, null, 2)}</pre></section></div><section><h3>{t("hosts.details.actions")}</h3><div className="module-section-toolbar">{capabilities.filter((item) => permissions.includes(item.permission)).map((item) => <button key={item.id} onClick={() => void review(item)}>{item.name}</button>)}{!value.approved && permissions.includes("hosts-manager.hosts.approve") && <button onClick={() => void api.approveHostsManagerHost(value.id).then(refresh)}><ShieldCheck />{t("hosts.action.approve")}</button>}</div></section>{plan && <Modal title={t("hosts.action.plan")} closeLabel={t("action.close")} onClose={() => setPlan(null)} footer={<><button onClick={() => setPlan(null)}>{t("action.cancel")}</button><button className="button-primary" onClick={() => void execute()}>{t("hosts.action.execute")}</button></>}><pre>{JSON.stringify(plan.value, null, 2)}</pre></Modal>}</Modal>;
}

function Groups({ items, canManage, t, toast, refresh }: { items: HostsManagerGroup[]; canManage: boolean; t: Translate; toast: ToastFn; refresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [name, setName] = useState("");
  async function save(event: React.FormEvent) { event.preventDefault(); try { await api.saveHostsManagerGroup({ name, description: "", parent_id: null, variables: {}, host_ids: [], active: true }); setName(""); setOpen(false); await refresh(); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error"); } }
  return <section className="ansible-panel"><header><div><h3>{t("hosts.groups.title")}</h3><p>{t("hosts.groups.hint")}</p></div>{canManage && <button onClick={() => setOpen(true)}><Plus />{t("hosts.group.add")}</button>}</header><div className="card-grid">{items.map((item) => <article className="data-card" key={item.id}><header><strong>{item.name}</strong></header><p>{item.description || t("common.none")}</p><small>{item.host_ids.length} {t("hosts.groups.hosts")}</small></article>)}</div>{open && <Modal title={t("hosts.group.add")} closeLabel={t("action.close")} onClose={() => setOpen(false)} footer={<button className="button-primary" type="submit" form="hosts-group-form">{t("action.save")}</button>}><form id="hosts-group-form" onSubmit={save}><label>{t("common.name")}<input autoFocus required value={name} onChange={(event) => setName(event.target.value)} /></label></form></Modal>}</section>;
}

function Enrollment({ items, groups, canManage, t, toast, refresh }: { items: HostsManagerEnrollmentToken[]; groups: HostsManagerGroup[]; canManage: boolean; t: Translate; toast: ToastFn; refresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [pattern, setPattern] = useState("node-*"); const [minutes, setMinutes] = useState(15); const [created, setCreated] = useState<HostsManagerEnrollmentToken | null>(null);
  async function create(event: React.FormEvent) { event.preventDefault(); try { const item = await api.createHostsManagerEnrollmentToken({ hostname_pattern: pattern, expires_minutes: minutes, port: 22, ssh_user: "algen-ansible", credential_id: null, environment: "", location: "", tags: [], group_ids: [], require_approval: true, onboard_ansible: false }); setCreated(item); setOpen(false); await refresh(); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error"); } }
  async function copy(value: string) { await navigator.clipboard.writeText(value); toast(t("hosts.enrollment.copied"), "ok"); }
  return <section className="ansible-panel"><header><div><h3>{t("hosts.enrollment.title")}</h3><p>{t("hosts.enrollment.hint")}</p></div>{canManage && <button className="button-primary" onClick={() => setOpen(true)}><Plus />{t("hosts.enrollment.generate")}</button>}</header><div className="table-scroll"><table><thead><tr><th>{t("hosts.enrollment.pattern")}</th><th>{t("hosts.enrollment.expires")}</th><th>{t("common.status")}</th><th>{t("column.actions")}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.hostname_pattern}</td><td>{new Date(item.expires_at * 1000).toLocaleString()}</td><td><Status value={item.used ? "used" : item.expired ? "expired" : item.revoked ? "revoked" : "active"} t={t} /></td><td>{canManage && !item.used && !item.expired && !item.revoked && <button onClick={() => void api.revokeHostsManagerEnrollmentToken(item.id).then(refresh)}><X />{t("hosts.enrollment.revoke")}</button>}</td></tr>)}</tbody></table></div>{open && <Modal title={t("hosts.enrollment.generate")} closeLabel={t("action.close")} onClose={() => setOpen(false)} footer={<button className="button-primary" type="submit" form="enrollment-form">{t("hosts.enrollment.generate")}</button>}><form id="enrollment-form" className="module-form-grid" onSubmit={create}><label>{t("hosts.enrollment.pattern")}<input value={pattern} onChange={(event) => setPattern(event.target.value)} /></label><label>{t("hosts.enrollment.minutes")}<input type="number" min="1" max="60" value={minutes} onChange={(event) => setMinutes(Number(event.target.value))} /></label><p className="wide">{t("hosts.enrollment.approvalHint")}</p><small className="wide">{groups.length} {t("hosts.groups.available")}</small></form></Modal>}{created?.command && <Modal title={t("hosts.enrollment.ready")} closeLabel={t("action.close")} onClose={() => setCreated(null)} footer={<><button onClick={() => void copy(created.command || "")}><Copy />{t("hosts.enrollment.copy")}</button><a className="button" href={created.script_url}><Download />{t("hosts.enrollment.download")}</a></>}><p>{t("hosts.enrollment.onceHint")}</p><pre>{created.command}</pre></Modal>}</section>;
}

function Operations({ items, t }: { items: HostsManagerOperation[]; t: Translate }) { return <div className="table-scroll"><table><thead><tr><th>{t("hosts.operation.action")}</th><th>{t("common.status")}</th><th>{t("hosts.operation.progress")}</th><th>{t("hosts.operation.time")}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.capability_id}</td><td><Status value={item.status} t={t} /></td><td>{item.progress}%</td><td>{new Date(item.created_at * 1000).toLocaleString()}</td></tr>)}</tbody></table>{!items.length && <div className="empty-state">{t("hosts.operations.empty")}</div>}</div>; }
function Records({ title, hint, items, t }: { title: string; hint: string; items: Array<Record<string, unknown>>; t: Translate }) { return <section className="ansible-panel"><header><div><h3>{title}</h3><p>{hint}</p></div></header><div className="card-grid">{items.map((item, index) => <article className="data-card" key={String(item.id || index)}><header><strong>{String(item.name || item.filename || item.id || t("common.none"))}</strong></header><pre>{JSON.stringify(item, null, 2)}</pre></article>)}</div>{!items.length && <div className="empty-state">{t("hosts.records.empty")}</div>}</section>; }
function Checks({ items, t }: { items: Array<{ id: string; status: string; message: string }>; t: Translate }) { return <section className="ansible-panel"><header><div><h3>{t("hosts.diagnostics.title")}</h3><p>{t("hosts.diagnostics.hint")}</p></div></header>{items.map((item) => <article className="module-diagnostic" key={item.id}><Status value={item.status} t={t} /><strong>{t(`hosts.diagnostics.${item.id}`)}</strong><span>{item.message}</span></article>)}</section>; }
function Placeholder({ section, t }: { section: ModuleSection; t: Translate }) { return <section className="ansible-panel"><header><div><h3>{t(`module.section.${section}`)}</h3><p>{t(`hosts.${section}.hint`)}</p></div></header><div className="empty-state">{t("hosts.section.apiReady")}</div></section>; }
function Status({ value, t }: { value: string; t: Translate }) { return <span className={`package-status ui-status-${value}`}>{t(`hosts.status.${value}`)}</span>; }
