import { RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { api, type AdminGroup, type AdminUser, type NetworkMount, type ResourceDashboard, type SambaStatus, type StoreApp, type SystemdService, type SystemLogs } from "../../api";
import type { Theme, ToastFn, Translate } from "../../app/types";
import type { Language } from "../../i18n";
import { formatSize } from "../files/utils";

function Shell({ title, subtitle, loading, t, onRefresh, children }: { title: string; subtitle: string; loading: boolean; t: Translate; onRefresh: () => void; children: React.ReactNode }) {
  return <section className="system-app"><header className="feature-header"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onRefresh}><RefreshCw className={loading ? "spin" : ""} />{t("action.refresh")}</button></header>{children}</section>;
}

function useLoader<T>(load: () => Promise<T>) {
  const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const refresh = async () => { setLoading(true); setError(""); try { setData(await load()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Error"); } finally { setLoading(false); } };
  // eslint-disable-next-line react-hooks/exhaustive-deps -- only the initial request belongs to this effect
  useEffect(() => { void refresh(); }, []);
  return { data, loading, error, refresh };
}

export function UsersApp({ t }: { t: Translate }) { const state = useLoader<AdminUser[]>(api.adminUsers); return <Shell title={t("app.users")} subtitle={t("users.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}>{state.data?.map((user) => <article className="data-row" key={user.username}><strong>{user.username}</strong><span>UID {user.uid}</span><span>{user.home}</span><span>{user.groups.join(", ")}</span></article>)}</DataState></Shell>; }
export function GroupsApp({ t }: { t: Translate }) { const state = useLoader<AdminGroup[]>(api.adminGroups); return <Shell title={t("app.groups")} subtitle={t("groups.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}>{state.data?.map((group) => <article className="data-row" key={group.name}><strong>{group.name}</strong><span>GID {group.gid}</span><span>{group.members.join(", ") || "—"}</span></article>)}</DataState></Shell>; }
export function MountsApp({ t }: { t: Translate }) { const state = useLoader<NetworkMount[]>(api.mounts); return <Shell title={t("app.networkMounts")} subtitle={t("mounts.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}>{state.data?.map((mount) => <article className="data-card" key={mount.id}><header><strong>{mount.name}</strong><span className={`status-badge ${mount.status}`}>{mount.status}</span></header><p>{mount.type.toUpperCase()} · {mount.host}:{mount.remote}</p><code>{mount.mount_point}</code>{mount.fs && <div className="usage-bar"><span style={{ width: `${mount.fs.used / mount.fs.total * 100}%` }} /></div>}</article>)}</DataState></Shell>; }
export function ServicesApp({ t }: { t: Translate }) { const state = useLoader<SystemdService[]>(api.systemdServices); return <Shell title={t("app.services")} subtitle={t("services.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}>{state.data?.map((service) => <article className="data-row" key={service.name}><strong>{service.name}</strong><span className={`status-badge ${service.status === "active" ? "completed" : "failed"}`}>{service.status}</span><span>{service.enabled}</span><span>{service.sub_state}</span></article>)}</DataState></Shell>; }
export function StoreAppView({ t }: { t: Translate }) { const state = useLoader<StoreApp[]>(api.apps); return <Shell title={t("app.store")} subtitle={t("store.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}><div className="card-grid">{state.data?.map((app) => <article className="data-card" key={app.id}><header><strong>{app.manifest.name}</strong><span className="status-badge">{app.manifest.version}</span></header><p>{app.manifest.description}</p><span>{app.status}</span></article>)}</div></DataState></Shell>; }
export function SambaAppView({ t }: { t: Translate }) { const state = useLoader<SambaStatus>(api.sambaStatus); return <Shell title={t("app.samba")} subtitle={t("samba.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}><div className="summary-grid"><article><span>{t("samba.installed")}</span><strong>{state.data?.installed ? t("common.yes") : t("common.no")}</strong></article><article><span>{t("samba.shares")}</span><strong>{state.data?.shares.length || 0}</strong></article></div>{state.data?.shares.map((share) => <article className="data-row" key={share.name}><strong>{share.name}</strong><code>{share.path}</code><span className={`status-badge ${share.enabled ? "completed" : "cancelled"}`}>{share.enabled ? t("common.enabled") : t("common.disabled")}</span></article>)}</DataState></Shell>; }
export function LogsAppView({ t }: { t: Translate }) { const state = useLoader<SystemLogs>(() => api.systemLogs(250)); return <Shell title={t("app.logs")} subtitle={t("logs.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}><pre className="log-view">{state.data?.lines.join("\n")}</pre></DataState></Shell>; }
export function MonitorApp({ t }: { t: Translate }) { const state = useLoader<ResourceDashboard>(api.resources); return <Shell title={t("app.monitor")} subtitle={t("monitor.subtitle")} loading={state.loading} t={t} onRefresh={() => void state.refresh()}><DataState state={state} t={t}>{state.data && <><div className="summary-grid"><Metric label={t("monitor.cpu")} value={`${state.data.cpu_percent ?? 0}%`} percent={state.data.cpu_percent || 0} /><Metric label={t("monitor.memory")} value={`${formatSize(state.data.ram.used)} / ${formatSize(state.data.ram.total)}`} percent={state.data.ram.percent} /><Metric label={t("monitor.swap")} value={`${formatSize(state.data.swap.used)} / ${formatSize(state.data.swap.total)}`} percent={state.data.swap.percent} /></div><div className="card-grid">{state.data.allowed_roots.map((disk) => <Metric key={disk.path} label={disk.path} value={`${formatSize(disk.used)} / ${formatSize(disk.total)}`} percent={disk.percent} />)}</div></>}</DataState></Shell>; }

function Metric({ label, value, percent }: { label: string; value: string; percent: number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong><div className="usage-bar"><span style={{ width: `${Math.min(100, percent)}%` }} /></div></article>; }
function DataState<T>({ state, t, children }: { state: { data: T | null; loading: boolean; error: string }; t: Translate; children: React.ReactNode }) { if (state.loading && !state.data) return <div className="loading-state">{t("status.loading")}</div>; if (state.error) return <div className="error-state">{state.error}</div>; return <div className="data-list">{children}</div>; }

export function SettingsAppView({ language, theme, t, onLanguage, onTheme }: { language: Language; theme: Theme; t: Translate; toast: ToastFn; onLanguage: (value: Language) => void; onTheme: (value: Theme) => void }) {
  return <section className="system-app"><header className="feature-header"><div><h2>{t("app.settings")}</h2><p>{t("settings.subtitle")}</p></div></header><div className="settings-cards"><article className="settings-card"><h3>{t("settings.appearance")}</h3><label className="field-label">{t("settings.theme")}<select value={theme} onChange={(event) => onTheme(event.target.value as Theme)}><option value="system">{t("settings.systemTheme")}</option><option value="light">{t("settings.light")}</option><option value="dark">{t("settings.dark")}</option></select></label><label className="field-label">{t("settings.language")}<select value={language} onChange={(event) => onLanguage(event.target.value as Language)}><option value="pl-PL">Polski</option><option value="en-US">English</option></select></label></article><article className="settings-card"><h3>{t("settings.accessibility")}</h3><p>{t("settings.accessibilityInfo")}</p></article></div></section>;
}
