import { request } from "../../../core/api/transport";
import type { AnsibleCredential, AnsibleDashboard, AnsibleEnrollmentToken, AnsibleExecution, AnsibleGroup, AnsibleHost, AnsiblePlaybook, AnsibleProject, AnsibleScan, AnsibleSchedule, AnsibleTemplate, AnsibleValidation, ModuleBackup, ModuleDiagnostic, ModuleJob } from "../../../core/api/contracts";

export const ansibleControllerClient = {
  ansibleDashboard: () => request<AnsibleDashboard>("/api/modules/ansible-controller/dashboard"),
  ansibleConfig: () => request<Record<string, unknown>>("/api/modules/ansible-controller/config"),
  saveAnsibleConfig: (payload: Record<string, unknown>) => request<{ job: ModuleJob }>("/api/modules/ansible-controller/config", { method: "PUT", body: JSON.stringify({ ...payload, confirm: true }) }),
  saveAnsibleManagedAccount: (payload: { username: string; sudo_profile: "none" | "nopasswd"; shell: "/bin/bash" | "/bin/sh"; comment: string; authorized_keys_mode: "exclusive"; key_rotation_days: number }) => request<{ managed_username: string; managed_sudo_profile: string; managed_shell: string; managed_comment: string; managed_authorized_keys_mode: string; managed_key_rotation_days: number }>("/api/modules/ansible-controller/managed-account", { method: "PUT", body: JSON.stringify({ ...payload, confirm: true }) }),
  ansibleHosts: () => request<AnsibleHost[]>("/api/modules/ansible-controller/hosts"),
  ansibleHost: (id: string) => request<AnsibleHost>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}`),
  saveAnsibleHost: (payload: Record<string, unknown>, id = "") => request<AnsibleHost>(id ? `/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/hosts", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  createAnsibleEnrollmentToken: (payload: { hostname_pattern: string; ssh_user: string; port: number; credential_id: string | null; environment: string; location: string; tags: string[]; expires_minutes: number }) => request<AnsibleEnrollmentToken>("/api/modules/ansible-controller/enrollment-tokens", { method: "POST", body: JSON.stringify(payload) }),
  deleteAnsibleHost: (id: string) => request<{ ok: boolean }>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  scanAnsibleHostKey: (id: string) => request<{ host_id: string; keys: Array<{ key_type: string; public_key: string; fingerprint: string }>; existing_fingerprint?: string | null; changed: boolean; requires_acceptance: boolean }>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}/ssh-key/scan`, { method: "POST", body: "{}" }),
  acceptAnsibleHostKey: (id: string, key: { public_key: string; fingerprint: string }, replace = false) => request<Record<string, unknown>>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}/ssh-key/accept`, { method: "POST", body: JSON.stringify({ ...key, replace, confirm: true }) }),
  testAnsibleHost: (id: string) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}/test`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  gatherAnsibleFacts: (id: string) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}/facts`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  rotateAnsibleHostKey: (id: string) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/hosts/${encodeURIComponent(id)}/managed-key/rotate`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  onboardAnsibleHost: (payload: Record<string, unknown>) => request<{ host: AnsibleHost; job: ModuleJob; onboarding_id: string }>("/api/modules/ansible-controller/onboarding", { method: "POST", body: JSON.stringify({ ...payload, confirm: true }) }),
  ansibleGroups: () => request<AnsibleGroup[]>("/api/modules/ansible-controller/groups"),
  saveAnsibleGroup: (payload: Record<string, unknown>, id = "") => request<AnsibleGroup>(id ? `/api/modules/ansible-controller/groups/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/groups", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  ansibleInventory: () => request<{ format: string; content: string }>("/api/modules/ansible-controller/inventory"),
  importAnsibleInventory: (content: string, format: "yaml" | "ini", confirm = false) => request<Record<string, unknown>>("/api/modules/ansible-controller/inventory/import", { method: "POST", body: JSON.stringify({ content, format, confirm }) }),
  ansibleScans: () => request<AnsibleScan[]>("/api/modules/ansible-controller/scans"),
  ansibleScan: (id: string) => request<AnsibleScan>(`/api/modules/ansible-controller/scans/${encodeURIComponent(id)}`),
  startAnsibleScan: (payload: Record<string, unknown>) => request<{ scan: AnsibleScan; job: ModuleJob; address_count: number }>("/api/modules/ansible-controller/scans", { method: "POST", body: JSON.stringify({ ...payload, confirm: true }) }),
  importAnsibleScan: (id: string, hostIds: string[], groupName = "") => request<{ hosts: AnsibleHost[]; imported: number }>(`/api/modules/ansible-controller/scans/${encodeURIComponent(id)}/import`, { method: "POST", body: JSON.stringify({ host_ids: hostIds, group_name: groupName, confirm: true }) }),
  ansibleCredentials: () => request<AnsibleCredential[]>("/api/modules/ansible-controller/credentials"),
  saveAnsibleCredential: (payload: Record<string, unknown>, id = "") => request<AnsibleCredential>(id ? `/api/modules/ansible-controller/credentials/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/credentials", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteAnsibleCredential: (id: string) => request<{ ok: boolean }>(`/api/modules/ansible-controller/credentials/${encodeURIComponent(id)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  ansibleProjects: () => request<AnsibleProject[]>("/api/modules/ansible-controller/projects"),
  saveAnsibleProject: (payload: Record<string, unknown>, id = "") => request<AnsibleProject>(id ? `/api/modules/ansible-controller/projects/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/projects", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  syncAnsibleProject: (id: string) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/projects/${encodeURIComponent(id)}/sync`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  ansiblePlaybooks: () => request<AnsiblePlaybook[]>("/api/modules/ansible-controller/playbooks"),
  validateAnsiblePlaybook: (payload: Record<string, unknown>) => request<AnsibleValidation>("/api/modules/ansible-controller/playbooks/validate", { method: "POST", body: JSON.stringify(payload) }),
  saveAnsiblePlaybook: (payload: Record<string, unknown>, id = "") => request<AnsiblePlaybook>(id ? `/api/modules/ansible-controller/playbooks/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/playbooks", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteAnsiblePlaybook: (id: string) => request<{ ok: boolean }>(`/api/modules/ansible-controller/playbooks/${encodeURIComponent(id)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) }),
  ansibleTemplates: () => request<AnsibleTemplate[]>("/api/modules/ansible-controller/templates"),
  saveAnsibleTemplate: (payload: Record<string, unknown>, id = "") => request<AnsibleTemplate>(id ? `/api/modules/ansible-controller/templates/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/templates", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  ansibleLaunchPlan: (id: string) => request<Record<string, unknown>>(`/api/modules/ansible-controller/templates/${encodeURIComponent(id)}/plan`),
  launchAnsibleTemplate: (id: string) => request<{ execution: AnsibleExecution; job: ModuleJob }>(`/api/modules/ansible-controller/templates/${encodeURIComponent(id)}/launch`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  ansibleJobs: () => request<AnsibleExecution[]>("/api/modules/ansible-controller/jobs"),
  ansibleJob: (id: string) => request<AnsibleExecution>(`/api/modules/ansible-controller/jobs/${encodeURIComponent(id)}`),
  cancelAnsibleJob: (id: string) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/jobs/${encodeURIComponent(id)}/cancel`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  retryAnsibleJob: (id: string) => request<{ execution: AnsibleExecution; job: ModuleJob }>(`/api/modules/ansible-controller/jobs/${encodeURIComponent(id)}/retry`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  ansibleSchedules: () => request<AnsibleSchedule[]>("/api/modules/ansible-controller/schedules"),
  saveAnsibleSchedule: (payload: Record<string, unknown>, id = "") => request<AnsibleSchedule>(id ? `/api/modules/ansible-controller/schedules/${encodeURIComponent(id)}` : "/api/modules/ansible-controller/schedules", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  ansibleFacts: (hostId = "") => request<Array<Record<string, unknown>>>(`/api/modules/ansible-controller/facts${hostId ? `?host_id=${encodeURIComponent(hostId)}` : ""}`),
  ansibleDiagnostics: () => request<{ diagnostics: ModuleDiagnostic[] }>("/api/modules/ansible-controller/diagnostics"),
  ansibleBackups: () => request<ModuleBackup[]>("/api/modules/ansible-controller/backups"),
  createAnsibleBackup: (description = "", includeCredentials = false) => request<{ job: ModuleJob }>("/api/modules/ansible-controller/backups", { method: "POST", body: JSON.stringify({ description, include_credentials: includeCredentials, confirm: true }) }),
  restoreAnsibleBackup: (id: string, checksum: string, includeCredentials = false) => request<{ job: ModuleJob }>(`/api/modules/ansible-controller/backups/${encodeURIComponent(id)}/restore`, { method: "POST", body: JSON.stringify({ checksum, include_credentials: includeCredentials, confirm: true }) }),
  deleteAnsibleBackup: (id: string) => request<{ ok: boolean }>(`/api/modules/ansible-controller/backups/${encodeURIComponent(id)}`, { method: "DELETE", body: JSON.stringify({ confirm: true }) })
} as const;
