import { useEffect, useId, useState } from "react";
import { api, type PackageModule, type PackagePlan } from "../../api";
import type { ToastFn, Translate } from "../../app/types";
import { Modal } from "../../components/Modal";
import type { PackageAction } from "./types";

export function PackageActionDialog({ item, action, t, toast, onClose, onStarted }: { item: PackageModule; action: PackageAction; t: Translate; toast: ToastFn; onClose: () => void; onStarted: () => void }) {
  const formId = `package-action-${useId().replace(/:/g, "")}`;
  const [removeData, setRemoveData] = useState(false); const [plan, setPlan] = useState<PackagePlan | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setLoading(true); setError(""); api.appPlan(item.id, action, removeData).then(setPlan).catch((reason) => setError(reason instanceof Error ? reason.message : t("error.generic"))).finally(() => setLoading(false)); }, [action, item.id, removeData, t]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!plan) return; setSaving(true); setError(""); try { await api.appAction(item.id, action, removeData); toast(t("store.actionQueued"), "ok", "admin"); onStarted(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("error.generic")); } finally { setSaving(false); } }
  return <Modal wide title={`${t(`store.${action}`)}: ${item.manifest.name}`} closeLabel={t("action.close")} onClose={onClose} footer={<><button type="button" onClick={onClose}>{t("action.cancel")}</button><button type="submit" form={formId} className={action === "uninstall" ? "button-danger" : "button-primary"} disabled={loading || saving || !plan}>{saving ? t("status.loading") : t("package.confirmOperation")}</button></>}><form id={formId} className="package-plan" onSubmit={(event) => void submit(event)} onKeyDown={(event) => event.stopPropagation()}><div className="package-plan-summary">{loading ? <div className="loading-state">{t("status.loading")}</div> : plan && <><dl><dt>{t("package.detectedSystem")}</dt><dd>{plan.distribution.name} · {plan.distribution.architecture} · {plan.distribution.package_manager || "—"}</dd><dt>{t("package.packages")}</dt><dd>{plan.packages.join(", ") || "—"}</dd><dt>{t("package.services")}</dt><dd>{plan.services.join(", ") || "—"}</dd><dt>{t("package.ports")}</dt><dd>{plan.ports.join(", ") || "—"}</dd><dt>{t("package.permissions")}</dt><dd>{plan.permissions.join(", ") || "—"}</dd></dl><h4>{t("package.planSteps")}</h4><ol>{plan.steps.map((step) => <li key={step}><code>{step}</code></li>)}</ol>{plan.warnings.length > 0 && <div className="package-warnings"><strong>{t("package.warnings")}</strong><ul>{plan.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}</>}</div>{action === "uninstall" && <label className="remove-data-option"><input type="checkbox" checked={removeData} onChange={(event) => setRemoveData(event.target.checked)} /><span><strong>{t("package.removeData")}</strong><small>{t("package.removeDataWarning")}</small></span></label>}{error && <p className="error-state compact-error" role="alert">{error}</p>}</form></Modal>;
}
