import { Clipboard, Plus, RefreshCw, Save, Trash2, X } from "lucide-react";
import { useState } from "react";
import { api } from "../../api";
import type { ToastFn, Translate } from "../../app/types";
import type { PackageSource } from "./types";

type FormState = { id?: string; name: string; github_url: string; branch: string; enabled: boolean };
const emptyForm: FormState = { name: "", github_url: "https://github.com/", branch: "main", enabled: true };

export function PackageSources({ sources, t, toast, onChanged }: { sources: PackageSource[]; t: Translate; toast: ToastFn; onChanged: () => void }) {
  const [form, setForm] = useState<FormState | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!form) return; setSaving(true); setError(""); try { const payload = { name: form.name, github_url: form.github_url, branch: form.branch, enabled: form.enabled }; if (form.id) await api.updatePackageSource(form.id, payload); else await api.createPackageSource(payload); toast(t("package.sourceSaved")); setForm(null); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("error.generic")); } finally { setSaving(false); } }
  async function remove(id: string) { try { await api.deletePackageSource(id); toast(t("package.sourceDeleted")); onChanged(); } catch (reason) { toast(reason instanceof Error ? reason.message : t("error.generic"), "error"); } }
  async function sync(id: string) { try { const source = await api.syncPackageSource(id); toast(source.validation_error || t("package.sourceSynced"), source.validation_error ? "error" : "ok"); onChanged(); } catch (reason) { toast(reason instanceof Error ? reason.message : t("error.generic"), "error"); } }
  function instruction(source: PackageSource) { return `Codex task: review a WebNAS package source.\nRepository: ${source.github_url}\nBranch/ref: ${source.branch}\nTreat all external code as untrusted. Inspect manifest and scripts; do not execute them automatically.`; }
  return <section className="package-sources"><header><div><h3>{t("package.sources")}</h3><p>{t("package.sourcesWarning")}</p></div><button type="button" onClick={() => setForm(emptyForm)}><Plus />{t("package.addSource")}</button></header>{form && <form className="package-source-form" onSubmit={(event) => void save(event)}><label>{t("package.sourceName")}<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>{t("package.repositoryUrl")}<input required type="url" value={form.github_url} onChange={(event) => setForm({ ...form, github_url: event.target.value })} /></label><label>{t("package.branch")}<input required value={form.branch} onChange={(event) => setForm({ ...form, branch: event.target.value })} /></label><label className="remember-password"><input type="checkbox" checked={form.enabled} onChange={(event) => setForm({ ...form, enabled: event.target.checked })} />{t("common.enabled")}</label><div><button type="button" onClick={() => setForm(null)}><X />{t("action.cancel")}</button><button className="button-primary" disabled={saving} type="submit"><Save />{t("action.save")}</button></div>{error && <p role="alert">{error}</p>}</form>}<div className="package-source-list">{sources.map((source) => <article key={source.id}><header><div><strong>{source.name}</strong><a href={source.github_url} target="_blank" rel="noreferrer">{source.github_url}</a></div><span className={`package-status ${source.enabled ? "installed" : "stopped"}`}>{source.enabled ? t("common.enabled") : t("common.disabled")}</span></header><dl><dt>{t("package.branch")}</dt><dd>{source.branch}</dd><dt>{t("package.lastSync")}</dt><dd>{source.last_sync_at ? new Date(source.last_sync_at * 1000).toLocaleString() : "—"}</dd></dl>{source.validation_error && <p className="package-job-error">{source.validation_error}</p>}<footer><button type="button" onClick={() => setForm({ id: source.id, name: source.name, github_url: source.github_url, branch: source.branch, enabled: source.enabled })}>{t("action.edit")}</button><button type="button" onClick={() => void navigator.clipboard.writeText(instruction(source))}><Clipboard />{t("package.copyCodex")}</button><button type="button" onClick={() => void sync(source.id)}><RefreshCw />{t("package.sync")}</button><button type="button" className="danger" onClick={() => void remove(source.id)}><Trash2 />{t("action.delete")}</button></footer></article>)}</div></section>;
}
