import { Clock, Plus, RefreshCw, RotateCcw, Trash2 } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import type { ToastFn } from "../../app/types";
import { confirmDialog } from "../../components/DialogService";
import { ntpManagerClient,type NtpSource,type NtpStatus } from "./api/client";
import "../infrastructure-managers.css";
type Props={permissions:string[];language:string;toast:ToastFn};
export function NtpManagerApp({permissions,toast}:Props){const[status,setStatus]=useState<NtpStatus|null>(null),[sources,setSources]=useState<NtpSource[]>([]),[server,setServer]=useState(""),[loading,setLoading]=useState(true);const refresh=useCallback(async()=>{try{const[s,p]=await Promise.all([ntpManagerClient.dashboard(),ntpManagerClient.sources()]);setStatus(s);setSources(p.items)}catch(e){toast(e instanceof Error?e.message:"NTP error","error","admin","ntp-manager")}finally{setLoading(false)}},[toast]);useEffect(()=>{void refresh()},[refresh]);async function act(fn:()=>Promise<unknown>){try{await fn();await refresh()}catch(e){toast(e instanceof Error?e.message:"NTP action failed","error","admin","ntp-manager")}}
return <div className="infra-manager-app"><header className="infra-manager-header"><div className="infra-manager-title"><Clock/><div><h2>NTP Manager</h2><p>Time synchronization, sources, offset and service state.</p></div></div><div className="infra-manager-actions">{permissions.includes("ntp.resync")&&<button onClick={()=>void act(ntpManagerClient.resync)}><RotateCcw/>Resync</button>}{permissions.includes("ntp.manage")&&<button onClick={async()=>{if(await confirmDialog("Restart NTP service?",k=>k))void act(()=>ntpManagerClient.service("restart"))}}>Restart</button>}<button onClick={()=>void refresh()}><RefreshCw className={loading?"spin":""}/>Refresh</button></div></header><div className="infra-stat-grid"><div className="infra-stat"><strong>{status?.synchronized?"Synchronized":"Not synchronized"}</strong><small>{status?.backend||"none"}</small></div><div className="infra-stat"><strong>{status?.stratum??"—"}</strong><small>Stratum</small></div><div className="infra-stat"><strong>{status?.offset||"—"}</strong><small>Offset</small></div><div className="infra-stat"><strong>{status?.timezone||"—"}</strong><small>Timezone</small></div><div className="infra-stat"><strong>{status?.service_state||"—"}</strong><small>{status?.service||"Service"}</small></div></div>{permissions.includes("ntp.manage")&&<div className="infra-manager-toolbar"><input placeholder="time.example.org" value={server} onChange={e=>setServer(e.target.value)}/><button onClick={()=>void act(async()=>{await ntpManagerClient.add(server.trim());setServer("")})} disabled={!server.trim()}><Plus/>Add server</button></div>}<div className="infra-table-wrap"><table className="infra-table"><thead><tr><th>Server</th><th>State</th><th>Selected</th><th>Stratum</th><th>Reach</th><th>Actions</th></tr></thead><tbody>{sources.map(s=><tr key={s.server}><td>{s.server}</td><td>{s.state||"configured"}</td><td>{s.selected?"yes":"no"}</td><td>{s.stratum??"—"}</td><td>{s.reach??"—"}</td><td><div className="infra-row-actions"><button onClick={async()=>{try{const r=await ntpManagerClient.test(s.server);toast(`${s.server}: ${r.ok?"OK":"failed"}`,r.ok?"success":"error","admin","ntp-manager")}catch(e){toast(e instanceof Error?e.message:"NTP test failed","error","admin","ntp-manager")}}>Test</button>{permissions.includes("ntp.manage")&&<button onClick={async()=>{if(await confirmDialog(`Remove ${s.server}?`,k=>k))void act(()=>ntpManagerClient.remove(s.server))}}><Trash2/>Delete</button>}</div></td></tr>)}</tbody></table></div></div>}
