"""Internal settings domain contracts used by the legacy compatibility router."""

from .rate_limit import AdminRateLimiter
from .schemas import (
    AdminChangePassword,
    AdminPassword,
    AdminSessionAction,
    AutoUpdatePatch,
    ChangePasswordRequest,
    ChownRequest,
    DesktopWidget,
    GroupCreate,
    GroupMember,
    GroupPatch,
    MAX_WALLPAPER_FILE_SIZE,
    MAX_WALLPAPER_FILES,
    MePatch,
    ServiceAction,
    ShutdownAction,
    ShutdownPolicy,
    UpdateAction,
    UpdateCompletionAck,
    UserCreate,
    UserPatch,
    UserQuota,
    UserSettings,
    validate_wallpaper,
)

__all__ = [
    "AdminChangePassword",
    "AdminPassword",
    "AdminRateLimiter",
    "AdminSessionAction",
    "AutoUpdatePatch",
    "ChangePasswordRequest",
    "ChownRequest",
    "DesktopWidget",
    "GroupCreate",
    "GroupMember",
    "GroupPatch",
    "MAX_WALLPAPER_FILE_SIZE",
    "MAX_WALLPAPER_FILES",
    "MePatch",
    "ServiceAction",
    "ShutdownAction",
    "ShutdownPolicy",
    "UpdateAction",
    "UpdateCompletionAck",
    "UserCreate",
    "UserPatch",
    "UserQuota",
    "UserSettings",
    "validate_wallpaper",
]
