export type FileItem = {
  name: string;
  path: string;
  type: string;
  is_dir: boolean;
  size: number;
  owner: string;
  group: string;
  mode: string;
  permissions: string;
  modified: number;
  mtime: number;
  mime: string;
  can_read: boolean;
  can_write: boolean;
  can_delete: boolean;
  can_rename: boolean;
  is_symlink: boolean;
  target?: string | null;
};
export type FileListResponse = {
  path: string;
  current_path: string;
  parent_path: string | null;
  items: FileItem[];
  page: number;
  page_size: number;
  total_items: number;
  total_pages: number;
  sort: string | null;
  direction: "asc" | "desc";
  can_write: boolean;
  can_upload: boolean;
  can_delete: boolean;
};
export type TextFileResponse = {
  path: string;
  content: string;
  encoding: "utf-8";
  size: number;
  mtime_ns: string;
};

export type Task = {
  id: string;
  username?: string;
  type: string;
  op: string;
  status: "queued" | "running" | "paused" | "completed" | "failed" | "cancelled";
  priority: number;
  created_at: number;
  source_paths: string[];
  destination_path: string;
  started_at: number | null;
  finished_at: number | null;
  paused_at: number | null;
  bytes_transferred: number;
  total_bytes: number;
  progress_percent: number;
  progress: number;
  speed_bps: number;
  speed_human: string;
  average_speed_bps: number;
  average_speed_human: string;
  eta_seconds: number | null;
  eta_human: string;
  current_file: string;
  files_done: number;
  files_total: number;
  rsync_exit_code: number | null;
  error_message: string;
  log_tail: string[];
  stderr_tail: string[];
  command_preview: string[];
  retry_count: number;
  errors: string[];
};

export type PinnedAppId = string;
export type InterfaceFont = "system" | "segoe" | "arial" | "verdana" | "tahoma" | "georgia" | "monospace";
export type WallpaperItem = { id: string; name: string; url: string; size: number; created_at: number };

export type UserPreferences = {
  language: "pl-PL" | "en-US";
  theme: "light" | "dark" | "system";
  startup_windows: "last" | "none";
  wallpaper: string;
  accent_color: "blue" | "teal" | "green" | "violet" | "rose" | "orange";
  wallpaper_fit: "cover" | "contain" | "stretch" | "center";
  taskbar_alignment: "left" | "center";
  pinned_apps: PinnedAppId[];
  pinned_modules: string[];
  start_pinned_apps: PinnedAppId[];
  desktop_shortcut_apps: PinnedAppId[];
  show_desktop_shortcuts: boolean;
  desktop_shortcut_size: "small" | "medium" | "large";
  show_welcome_widget: boolean;
  show_notifications: boolean;
  show_transfer_indicator: boolean;
  show_background_actions_indicator: boolean;
  window_transparency: boolean;
  animations_enabled: boolean;
  clock_show_seconds: boolean;
  date_format: "locale" | "short" | "long" | "iso";
  time_format: "12" | "24";
  interface_scale: number;
  interface_font: InterfaceFont;
  larger_text: boolean;
  high_contrast: boolean;
  reduced_motion: boolean;
  strong_active_borders: boolean;
  always_show_focus: boolean;
  file_default_view: "list" | "grid" | "large";
  file_compact_rows: boolean;
  file_show_hidden: boolean;
  file_confirm_delete: boolean;
  file_confirm_overwrite: boolean;
  file_page_size: 25 | 50 | 100 | 200;
  file_default_sort: "name" | "size" | "type" | "modified";
  file_sort_direction: "asc" | "desc";
  file_remember_last_path: boolean;
  transfer_success_notifications: boolean;
  transfer_error_notifications: boolean;
  transfer_open_failed_details: boolean;
  transfer_remember_filter: boolean;
  notification_transfer: boolean;
  notification_errors: boolean;
  notification_admin: boolean;
  notification_auto_hide: boolean;
  notification_limit: number;
  first_day_of_week: "monday" | "sunday" | "locale";
  widgets_enabled: boolean;
  desktop_widgets: DesktopWidget[];
};

export type DesktopWidgetId = "cpu" | "ram" | "disks" | "transfers" | "services" | "alerts";
export type DesktopWidget = { id: DesktopWidgetId; visible: boolean; x: number; y: number; width: number; height: number };

export type SettingsMe = UserPreferences & {
  username: string;
  uid: number;
  gid: number;
  groups: string[];
  home: string;
  shell: string;
  gecos: string;
  is_admin: boolean;
  role: "admin" | "operator" | "auditor" | "user";
  role_source: string;
  permissions: string[];
};

export type SettingsPatch = Partial<UserPreferences>;

export type AdminUser = SettingsMe & { is_system: boolean; manageable: boolean };
export type AdminGroup = { name: string; gid: number; members: string[] };
export type SystemStatus = { service: string; version: string; port: number; data_dir: string; log_dir: string; temp_dir: string };
export type HostInfo = {
  hostname: string;
  operating_system: string;
  kernel_version: string;
  architecture: string;
  ip_addresses: string[];
  application_version: string;
  uptime_seconds: number | null;
  cpu: { model: string; physical_cores: number | null; logical_threads: number | null };
  memory: UsageMetric;
  gpus: string[];
  storage: UsageMetric & { path: string } | null;
};
export type UpdateStatus = { branch: string; local: string; remote: string; installed_version?: string | null; available_version?: string | null; update_available: boolean; available?: boolean; error?: string; source?: string; source_url?: string; released_at?: number | null; checked_at?: number };
export type UpdateBlocker = { id: string; type: string; status: "queued" | "running"; started_at: number | null; progress: number | null; description: string };
export type UpdateStepStatus = "pending" | "running" | "success" | "failed" | "skipped";
export type UpdateStep = { id: string; status: UpdateStepStatus; message: string; started_at: number | null; finished_at: number | null; error?: string | null };
export type UpdateProgress = {
  id?: string | null;
  state: "idle" | "waiting" | "preparing" | "running" | "completed" | "failed";
  phase?: string;
  failed_phase?: string | null;
  running: boolean;
  progress?: number | null;
  pid: number | null;
  unit?: string | null;
  exit_code: number | null;
  requested_at?: number | null;
  started_at: number | null;
  finished_at: number | null;
  previous_version?: string | null;
  target_version?: string | null;
  current_version?: string | null;
  commit_revision?: string | null;
  message?: string;
  steps?: UpdateStep[];
  trigger?: "manual" | "automatic";
  updated_at?: number | null;
  active_count?: number;
  blockers?: UpdateBlocker[];
  log: string;
  lines: string[];
};
export type UpdateStart = UpdateProgress & { ok: boolean; updated?: boolean; skipped?: boolean; reason?: string };
export type UpdateCompletionNotice = {
  id: string;
  previous_version: string | null;
  current_version: string | null;
  finished_at: number | null;
  commit_revision: string | null;
  commit_date: number | null;
};
export type AutoUpdateSettings = {
  check_enabled: boolean;
  enabled: boolean;
  interval_hours: number;
  update_config: boolean;
  npm_audit_fix?: boolean;
  last_checked: number | null;
  last_run: number | null;
  last_error: string;
  last_pid: number | null;
  next_check: number | null;
};
export type SystemLogs = { source: string; lines: string[] };
export type LogEntry = {
  id: string;
  timestamp: string | null;
  original_priority?: number;
  original_severity?: "emergency" | "alert" | "critical" | "error" | "warning" | "notice" | "info" | "debug";
  priority: number;
  severity: "emergency" | "alert" | "critical" | "error" | "warning" | "notice" | "info" | "debug";
  severity_inferred?: boolean;
  severity_reason?: string | null;
  source: string;
  unit: string;
  identifier: string;
  hostname: string;
  pid: number | null;
  uid: number | null;
  message: string;
  cursor: string;
  fields: Record<string, unknown>;
};
export type LogSource = { id: string; label: string; available: boolean; status: string; permission: string };
export type LogSourceGroup = { id: string; label: string; items: LogSource[] };
export type LogSourcesResponse = { groups: LogSourceGroup[]; capabilities: { journal: boolean; docker: boolean; live: boolean; export: boolean } };
export type LogQuery = {
  source?: string; query?: string; regex?: boolean; case_sensitive?: boolean; negate?: boolean; message_only?: boolean;
  priority?: number[]; unit?: string; pid?: number | null; uid?: number | null; identifier?: string; transport?: string;
  hostname?: string; device?: string; username?: string; group?: string; boot_id?: string; container_id?: string;
  since?: number | null; until?: number | null; cursor?: string;
  direction?: "older" | "newer"; limit?: number;
};
export type LogEntriesResponse = { items: LogEntry[]; next_cursor: string | null; has_more: boolean; direction: string; limit: number; truncated: boolean };
export type LogBoot = { id: string; index: number; first: string | null; last: string | null; duration_seconds?: number | null; current: boolean };
export type LogService = { unit: string; load: string; active: string; sub: string; description: string };
export type LogContainer = { id: string; name: string; image: string; state: string; status: string };
export type LogSavedView = {
  id: string; name: string; source: string; query: string; filters: Record<string, string | number | boolean | number[]>;
  columns: string[]; sort: "newest" | "oldest"; view_mode: "compact" | "table"; builtin: boolean;
};
export type ActivityCategory = "login" | "file" | "configuration" | "administration" | "module";
export type ActivityStatus = "success" | "failure" | "info" | "queued" | "cancelled";
export type ActivityEvent = {
  id: number;
  created_at: number;
  actor: string;
  category: ActivityCategory;
  action: string;
  target: string;
  status: ActivityStatus;
  summary: string;
  details: Record<string, unknown>;
  source: string;
};
export type ActivityResponse = {
  items: ActivityEvent[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
  scope: "own" | "global";
};
export type ActivitySummary = {
  total: number;
  categories: Record<ActivityCategory, number>;
  statuses: Record<ActivityStatus, number>;
  latest_at: number | null;
  scope: "own" | "global";
};
export type SystemdService = {
  name: string;
  status: string;
  sub_state: string;
  enabled: string;
  uptime_seconds: number | null;
  last_error: string;
  managed_by_webnas: boolean;
};
export type UsageMetric = { total: number; used: number; free: number; percent: number };
export type DiskMetric = UsageMetric & {
  path: string;
  paths?: string[];
  filesystem_id?: string;
  device?: string | null;
  mountpoint?: string | null;
  fs_type?: string | null;
  read_bytes_per_sec?: number | null;
  write_bytes_per_sec?: number | null;
  read_bytes?: number;
  write_bytes?: number;
};
export type NetworkMetric = {
  name: string;
  state: "up" | "down" | "unknown";
  rx_bytes: number;
  tx_bytes: number;
  rx_bytes_per_sec: number | null;
  tx_bytes_per_sec: number | null;
  system: boolean;
};
export type DiskIoMetric = {
  device: string;
  read_bytes: number;
  write_bytes: number;
  read_bytes_per_sec: number | null;
  write_bytes_per_sec: number | null;
};
export type ResourceAlert = { code: string; severity: "info" | "warning" | "critical"; target: string; value: number | string };
export type ProcessMetric = { pid: number; user: string; name: string; cpu_percent: number; memory_percent: number; rss: number; state: string };
export type ResourceDashboard = {
  scope: "admin" | "user";
  timestamp: number;
  cpu_percent: number | null;
  cpu_cores: Array<number | null>;
  cpu_logical_cores: number;
  cpu_frequency_mhz: number | null;
  ram: UsageMetric;
  swap: UsageMetric;
  allowed_roots: DiskMetric[];
  mountpoints: DiskMetric[];
  uptime_seconds: number | null;
  load_average: number[] | null;
  temperature_c: number | null;
  webnas_service: string | null;
  hostname: string;
  os_name: string;
  kernel_version: string;
  boot_time: number | null;
  network_interfaces: NetworkMetric[];
  disk_io: DiskIoMetric[];
  alerts: ResourceAlert[];
  processes: ProcessMetric[];
  warnings: string[];
};
export type AppJob = {
  id: string;
  app_id?: string;
  module_id: string;
  action: string;
  status: "queued" | "running" | "completed" | "failed" | "cancelled";
  progress: number;
  created_at: number;
  finished_at?: number | null;
  log_tail: Array<{ id: number; created_at: number; stream: string; line: string }>;
  error: string;
  current_step?: string;
  stage?: string;
  requested_by?: string;
  operation?: string;
  warnings?: string[];
  result?: Record<string, unknown>;
  cancellation_requested?: boolean;
  cancellable?: boolean;
  requires_reboot?: boolean;
  plan?: PackagePlan;
};
export type PackageManifest = {
  id: string;
  name: string;
  description: string;
  long_description: string;
  category: string;
  version: string;
  maintainer: string;
  homepage?: string | null;
  icon: string;
  screenshots: string[];
  license: string;
  supported_distributions: string[];
  supported_architectures: string[];
  apt_packages: string[];
  dnf_packages: string[];
  systemd_services: string[];
  ports: string[];
  dependencies: string[];
  conflicts: string[];
  permissions: string[];
  config_paths: string[];
  data_paths: string[];
  backup_paths: string[];
  proxmox_safe: boolean;
  requires_reboot: boolean;
  requires_root: boolean;
  configurable: boolean;
  removable: boolean;
  changelog: string[];
  packages?: { apt: string[]; dnf: string[]; yum: string[] };
  installations?: Record<string, { type: "system_package" | "command" | "download_package" | "unsupported"; packages: string[]; script?: string | null; url?: string | null; package_format?: "deb" | "rpm" | null; reason: string }>;
  services?: Array<{ name: string; required: boolean }>;
  config?: { primary_file?: string | null; backup_paths: string[]; validation_command: string[] };
  capabilities?: ModuleCapability;
};

export type ModuleCapability = {
  install: boolean; update: boolean; uninstall: boolean; configure: boolean; service_control: boolean; reload: boolean;
  logs: boolean; diagnostics: boolean; backups: boolean; import_export: boolean; healthcheck: boolean;
  resources: string[]; actions: string[];
};
export type ModuleResource = { resource: string; items: Array<Record<string, unknown>>; total: number; [key: string]: unknown };
export type ModuleConnection = { base_url: string; username: string; secret_configured: boolean };
export type RbacRole = "admin" | "operator" | "auditor" | "user";
export type RbacAssignment = { username: string; uid?: number; role: RbacRole; allow: string[]; deny: string[]; permissions: string[]; role_source: string; is_admin: boolean };
export type RbacRoles = { roles: Record<RbacRole, string[]>; permissions: string[] };
export type PermissionRisk = "low" | "medium" | "high" | "critical";
export type PermissionMetadata = { id: string; category: string; operation: string; applications: string[]; risk: PermissionRisk; mutating: boolean; label_key: string; description_key: string };
export type IdentityProfile = { username: string; role: RbacRole; role_source: "linux-admin" | "assignment" | "default"; linux_admin: boolean; is_admin: boolean; permissions: string[]; effective_permissions?: string[]; denied_permissions: string[]; permission_sources: Record<string, string[]> };
export type IdentityUser = IdentityProfile & { uid: number; gid: number; primary_group: string; supplementary_groups: string[]; groups: string[]; home: string; shell: string; gecos: string; locked: boolean; password_change_required: boolean; is_system: boolean; manageable: boolean; allow: string[]; deny: string[] };
export type IdentityGroup = { name: string; groupname: string; gid: number; primary_users: string[]; supplementary_members: string[]; members: string[]; is_system: boolean; protected: boolean; manageable: boolean; allow: string[]; deny: string[]; inheriting_users: string[]; inheriting_count: number };
export type IdentityRoles = { roles: Record<RbacRole, string[]>; permissions: PermissionMetadata[] };
export type IdentityHistory = { id: number; created_at: number; actor: string; subject_type: "user" | "group" | "migration"; subject: string; action: string; previous: Record<string, unknown>; current: Record<string, unknown>; status: string; error_code: string };
export type ModuleManifest = PackageManifest;
export type ModuleHealth = "healthy" | "degraded" | "failed" | "unknown" | "not_installed";
export type ModuleStatus = {
  installed: boolean;
  package_version?: string | null;
  available_version?: string | null;
  update_available: boolean;
  service_state: string;
  service_enabled: boolean;
  services: Record<string, { state: string; enabled: boolean; required: boolean; uptime_seconds?: number | null }>;
  configuration_valid?: boolean | null;
  health: ModuleHealth;
  health_message: string;
  last_action: string;
  last_action_status: string;
  last_action_time?: number | null;
  last_error: string;
  metrics: Record<string, unknown>;
};
export type ModuleJob = AppJob;
export type ModuleJobStage = string;
export type CronEnvironmentVariable = { name: string; value: string };
export type CronJobSource = "webnas" | "user_crontab" | "system_crontab" | "cron_d" | "system";
export type CronJobStatus = "enabled" | "disabled" | "external" | "invalid";
export type CronJob = {
  id: string;
  name: string;
  description: string;
  user: string;
  schedule: string;
  command: string;
  working_directory: string | null;
  environment: CronEnvironmentVariable[];
  timeout_seconds: number | null;
  enabled: boolean;
  source: CronJobSource;
  status: CronJobStatus;
  read_only: boolean;
  created_at: number | null;
  updated_at: number | null;
  created_by: string;
  updated_by: string;
  last_run_at: number | null;
  last_run_status: string | null;
  next_run_at: number | null;
  source_label: string;
};
export type CronJobInput = Pick<CronJob, "name" | "description" | "user" | "schedule" | "command" | "working_directory" | "environment" | "timeout_seconds" | "enabled">;
export type CronDashboard = { active: number; inactive: number; errors: number; recently_run: number; total: number };
export type CronManagerStatus = {
  installed: boolean;
  crontab_available: boolean;
  daemon: string | null;
  service_state: string;
  service_enabled: boolean | null;
  configuration_valid: boolean | null;
  timezone: string;
  config_path: string;
  blocked_by_proxmox: boolean;
  dashboard: CronDashboard;
};
export type CronValidation = { valid: boolean; normalized: string; explanation: string; next_run_at: number | null; generated_entry: string; warnings: string[] };
export type CronDiagnostic = { code: string; status: string; title: string; detail: string; recommendation: string };
export type CronLogEntry = { source: string; message: string; timestamp: string | null };
export type ModuleConfig = Record<string, unknown>;
export type ModuleValidationResult = { ok: boolean; errors: string[]; warnings: string[]; changes: Array<{ kind: string; name: string; before?: unknown; after?: unknown }>; generated_config: string; validator_output: string; confirmations_required: string[] };
export type ModuleApplyPlan = { validation: ModuleValidationResult; steps: string[]; services: string[]; config_paths: string[]; warnings: string[] };
export type ModuleDiagnostic = { status: "ok" | "info" | "warning" | "critical"; title: string; description: string; details: string; severity: "ok" | "info" | "warning" | "critical"; recommended_action: string };
export type ModuleBackup = { id: string; module_id: string; created_at: number; created_by: string; description: string; automatic: boolean; checksum: string; package_version: string; size: number; files: string[] };
export type ModuleLogSource = { id: string; label: string };
export type ModuleSummary = PackageModule & { module_status: ModuleStatus; capabilities: ModuleCapability; active_job?: ModuleJob | null };
export type OsRepository = { id: string; name: string; description: string; kind: "local" | "mirror"; format: "apt" | "rpm"; distribution: string; distribution_version: string; architectures: string[]; source_url: string; active: boolean; schedule: string; retention_count: number; signing_key_id?: string | null; allow_private_network: boolean; allow_private_http: boolean; auth_type: "none" | "bearer" | "basic"; auth_username: string; auth_secret_configured: boolean; last_sync_at?: number | null; last_sync_status: string; package_count: number; size_bytes: number; channels?: OsRepositoryChannel[] };
export type OsRepositoryPackage = { id: string; repository_id: string; name: string; version: string; release: string; epoch: string; architecture: string; format: "apt" | "rpm"; distribution: string; size_bytes: number; sha256: string; signed: boolean; signature_status: string; maintainer: string; vendor: string; description: string; license: string; dependencies: string[]; conflicts: string[]; source: string; blocked: boolean; created_at: number };
export type OsRepositorySnapshot = { id: string; repository_id: string; name: string; description: string; package_count: number; logical_size: number; physical_size: number; archived: boolean; created_at: number; packages?: OsRepositoryPackage[] };
export type OsRepositoryChannel = { id: string; repository_id: string; repository_name?: string; name: "incoming" | "testing" | "production" | "archive"; snapshot_id?: string | null; previous_snapshot_id?: string | null; updated_at: number };
export type OsRepositoryJob = { id: string; repository_id: string; operation: string; status: "queued" | "running" | "completed" | "failed" | "cancelled"; stage: string; progress: number; current_item: string; downloaded_count: number; downloaded_bytes: number; speed_bps: number; warnings: string[]; error: string; created_at: number; started_at?: number | null; finished_at?: number | null; logs?: Array<{ id: number; stream: string; line: string; created_at: number }> };
export type OsRepositoryDashboard = { repositories: number; packages: number; snapshots: number; published_channels: number; hosts: number; pending_packages: number; running_jobs: number; errors: number; size_bytes: number; recent_jobs: OsRepositoryJob[]; expiring_keys: OsRepositoryKey[] };
export type OsRepositoryKey = { id: string; name: string; fingerprint: string; public_key: string; secret_configured: boolean; expires_at?: number | null; status: string; created_at: number };
export type OsRepositoryAssignment = { id: string; repository_id: string; repository_name: string; channel: string; host_id?: string | null; group_id?: string | null; format: string; distribution: string; distribution_version: string; created_at: number };
export type OsRepositoryPage<T> = { items: T[]; page: number; page_size: number; total: number };
export type AnsibleDashboard = {
  hosts: number; hosts_online: number; hosts_unreachable: number; host_key_errors: number; groups: number; projects: number;
  playbooks: number; templates: number; active_jobs: number; failed_jobs: number; scheduled: number; ansible_version?: string;
  controller_user_ready?: boolean; last_scan?: Record<string, unknown> | null; last_git_sync?: Record<string, unknown> | null;
};
export type AnsibleHost = {
  id: string; name: string; address: string; port: number; ssh_user: string; credential_id?: string | null;
  python_interpreter: string; connection_type: "ssh" | "paramiko"; environment: string; location: string; tags: string[];
  variables: Record<string, unknown>; fingerprint_status: string; last_test_at?: number | null; last_facts_at?: number | null;
  last_error: string; managed_user_created: boolean; active: boolean; groups?: Array<{ id: string; name: string }>;
  facts?: Record<string, unknown>; created_at: number; updated_at: number;
};
export type AnsibleEnrollmentToken = { id: string; token: string; hostname_pattern: string; expires_at: number };
export type AnsibleGroup = { id: string; name: string; description: string; parent_id?: string | null; variables: Record<string, unknown>; host_ids: string[]; active: boolean; created_at: number; updated_at: number };
export type AnsibleCredential = { id: string; name: string; type: "ssh_private_key" | "ssh_password" | "become_password" | "git_private_key" | "awx_token" | "vault_secret"; username: string; description: string; secret_configured: boolean; active: boolean; created_at: number; updated_at: number };
export type AnsibleProject = { id: string; name: string; source_type: "editor" | "git" | "archive" | "managed_directory"; repository_url: string; revision: string; credential_id?: string | null; sync_before_run: boolean; allow_submodules: boolean; last_commit: string; last_sync_at?: number | null; last_sync_status: string; active: boolean };
export type AnsibleRisk = { code: string; message: string; path?: string; line?: number | null };
export type AnsiblePlaybook = { id: string; project_id: string; name: string; filename: string; content: string; current_version: number; risk_status: string; warnings: AnsibleRisk[]; active: boolean; updated_at: number };
export type AnsibleTemplate = { id: string; name: string; description: string; project_id: string; playbook_id: string; host_ids: string[]; group_ids: string[]; ssh_credential_id?: string | null; become_credential_id?: string | null; vault_credential_id?: string | null; limit_pattern: string; tags: string[]; skip_tags: string[]; check_mode: boolean; diff_mode: boolean; verbosity: number; forks: number; timeout_seconds: number; extra_vars: string; concurrency_policy: string; sync_before_run: boolean; confirmation_required: boolean; active: boolean };
export type AnsibleHostResult = { id: string; host_id?: string | null; host_name: string; status: string; ok_count: number; changed_count: number; failed_count: number; unreachable_count: number; skipped_count: number; rescued_count: number; ignored_count: number; message: string };
export type AnsibleExecution = { id: string; package_job_id?: string | null; template_id?: string | null; retry_of?: string | null; requested_by: string; status: string; stage: string; host_ids: string[]; warnings: AnsibleRisk[]; summary: Record<string, number>; stdout: string; stderr: string; exit_code?: number | null; started_at?: number | null; finished_at?: number | null; created_at: number; host_results?: AnsibleHostResult[] };
export type AnsibleScanHost = { id: string; address: string; hostname: string; port: number; latency_ms?: number | null; ssh_status: string; imported_host_id?: string | null };
export type AnsibleScan = { id: string; request: Record<string, unknown>; status: string; progress: number; discovered: number; package_job_id?: string | null; error: string; created_at: number; hosts?: AnsibleScanHost[] };
export type AnsibleSchedule = { id: string; name: string; template_id: string; kind: "once" | "hourly" | "daily" | "weekly" | "monthly" | "cron"; expression: string; timezone: string; missed_policy: "skip" | "run_once"; next_run_at?: number | null; last_run_at?: number | null; active: boolean };
export type AnsibleValidation = { ok: boolean; errors: AnsibleRisk[]; warnings: AnsibleRisk[]; blocked: AnsibleRisk[]; task_count: number; documents?: number };
export type HostsManagerDashboard = {
  generated_at?: number;
  total: number; online: number; offline: number; errors?: number; unverified: number; fingerprint_errors: number;
  pending_approval: number; pending_registration?: number; ansible_available: number; power_managed: number;
  available_updates?: number; security_updates?: number; without_agent?: number; stale_reports?: number;
  low_disk?: number; high_cpu?: number; high_memory?: number; by_environment?: Record<string, number>;
  recent_hosts?: HostsManagerHost[]; recent_connections?: HostsManagerHost[]; onboarding_history?: HostsManagerOperation[];
  hostname_changes?: HostsManagerOperation[]; administrative_operations?: HostsManagerOperation[];
  recent_operations: HostsManagerOperation[]; recent_errors: HostsManagerHost[];
};
export type HostsManagerAgent = {
  id: string; host_id: string; installation_id: string; agent_version: string; status: string;
  communication_port: number; report_interval_seconds: number; installed_at: number;
  last_heartbeat_at?: number | null; last_report_at?: number | null; last_error: string; certificate_status: string;
};
export type HostsManagerHost = AnsibleHost & {
  hostname: string; fqdn: string; management_address: string; description: string; approved: boolean;
  registration_status: string; connection_status: string; power_status: string; enrollment_source: string;
  group_ids: string[]; status?: string; distribution?: string; system_version?: string; agent_version?: string;
  agent_status?: string; available_updates?: number; security_updates?: number; agent?: HostsManagerAgent | null;
  identity?: Record<string, unknown> | null; latest_report?: Record<string, Record<string, unknown>>;
  environment_details?: HostsManagerEnvironment | null; capabilities?: HostsManagerCapability[];
};
export type HostsManagerGroup = AnsibleGroup & {
  managed?: boolean;
  managed_by?: { apmid_id: string; environment_id: string } | null;
};
export type HostsManagerCredentialType = AnsibleCredential["type"] | "username_password" | "api_token" | "generic_secret" | "redfish" | "ipmi" | "proxmox_api" | "wol";
export type HostsManagerCredential = Omit<AnsibleCredential, "type"> & {
  type: HostsManagerCredentialType;
  environment_id?: string | null; last_used_at?: number | null; host_count?: number; shared_with: string[];
};
export type HostsManagerCapability = { id: string; name: string; icon: string; permission: string; module_id: string; deep_link: string };
export type HostsManagerOperation = { id: string; host_id?: string | null; capability_id: string; module_id: string; status: string; stage: string; progress: number; package_job_id?: string | null; error: string; details: Record<string, unknown>; created_at: number; updated_at: number };
export type HostsManagerBootstrapOS = "linux" | "windows";
export type HostsManagerEnvironment = {
  id: string; name: string; slug: string; description: string; color: string; default_hostname_pattern_id?: string | null;
  default_credential_id?: string | null; default_agent_port: number; report_interval_seconds: number; active: boolean;
  host_count: number; created_at: number; updated_at: number;
};
export type HostsManagerApmid = {
  id: string; code: string; description: string; active: boolean;
  created_at: number; updated_at: number; created_by: string; updated_by: string;
  environment_groups: Array<{
    environment_id: string; environment_name: string; environment_slug: string;
    group_id: string; group_name: string; active: boolean;
  }>;
};

export type ApmidResourcePermission = "view" | "update" | "members.view" | "members.manage" | "permissions.view" | "permissions.manage" | "audit.view" | "delete";
export type ApmidRole = "viewer" | "operator" | "manager" | "owner";
export type ApmidItem = {
  id: string; code: string; name: string; description: string; active: boolean;
  business_owner: string | null; member_count: number; related_count?: number;
  created_at: number; updated_at: number; created_by: string; updated_by: string;
  effective_permissions?: { username: string; role: ApmidRole | null; allow: ApmidResourcePermission[]; deny: ApmidResourcePermission[]; effective: ApmidResourcePermission[]; sources: Record<ApmidResourcePermission, string> };
};
export type ApmidMember = {
  apmid_id: string; username: string; role: ApmidRole; assigned_at: number; assigned_by: string; updated_at: number; updated_by: string;
  status: "active" | "locked" | "missing";
  permissions: { username: string; role: ApmidRole; allow: ApmidResourcePermission[]; deny: ApmidResourcePermission[]; effective: ApmidResourcePermission[]; sources: Record<ApmidResourcePermission, string> };
};
export type ApmidHistory = { id: number; apmid_id: string | null; action: string; actor: string; target: string; details: Record<string, unknown>; created_at: number };
export type ApmidDashboard = { total: number; active: number; members: number; without_owner: number; recent: ApmidHistory[] };
export type ApmidBackup = { id: string; schema_version: number; created_at: number; created_by: string; description: string; sha256: string; database: string };
export type HostsManagerHostnamePattern = {
  id: string; name: string; prefix: string; suffix: string; digits: number; start_value: number; step: number;
  next_value: number; last_value?: number | null; description: string; active: boolean; template: string;
  next_hostname: string; preview_hostnames: string[]; created_at: number; updated_at: number;
};
export type HostsManagerSettings = {
  hostname_template: string; next_hostname: string; sequence_width: number; preview_hostnames: string[];
  bootstrap_default_os: HostsManagerBootstrapOS; bootstrap_apply_hostname: boolean;
  default_hostname_pattern_id?: string | null; agent_default_port: number; server_url: string; agent_protocol: "https" | "wss";
  connection_timeout_seconds: number; report_interval_seconds: number; heartbeat_interval_seconds: number;
  max_connection_retries: number; ssh_default_port: number; ssh_timeout_seconds: number; ssh_max_concurrency: number;
  ssh_verify_fingerprint: boolean; ssh_new_host_key_policy: "ask" | "reject" | "accept_new";
  agent_min_version: string; agent_auto_update: boolean; agent_update_channel: "stable" | "beta" | "pinned";
  agent_repository_url: string; agent_enforce_tls: boolean; agent_log_level: "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL";
  token_ttl_minutes: number; allowed_registration_networks: string[]; max_auth_failures: number;
  updated_at: number; updated_by: string;
};
export type HostsManagerSettingsUpdate = Omit<HostsManagerSettings, "next_hostname" | "sequence_width" | "preview_hostnames" | "updated_at" | "updated_by">;
export type HostsManagerEnrollmentInput = {
  bootstrap_os: HostsManagerBootstrapOS; apply_hostname: boolean; expires_minutes?: number | null;
  apmid_id: string; environment_id: string; location: string; tags: string[]; group_ids: string[];
  require_approval: boolean; onboard_ansible: boolean; mode?: "one_time" | "permanent";
  hostname_pattern_id?: string | null; bound_address?: string; agent_port?: number | null; report_interval_seconds?: number | null;
};
export type HostsManagerEnrollmentToken = {
  id: string; hostname_pattern: string; assigned_hostname: string; bootstrap_os: HostsManagerBootstrapOS;
  apply_hostname: boolean; expires_at: number; created_at?: number; created_by?: string; used_hostname?: string;
  used: boolean; expired?: boolean; revoked?: boolean; mode?: "one_time" | "permanent"; hostname_pattern_id?: string | null;
  bound_address?: string; agent_port?: number; report_interval_seconds?: number; token?: string; script_url?: string;
  command?: string; filename?: string;
  apmid_id?: string | null; apmid_code?: string | null; environment_id?: string | null;
  environment_name?: string | null; environment_slug?: string | null;
  managed_group_id?: string | null; managed_group_name?: string | null; group_ids?: string[];
};
export type HostsManagerRepository = { id: string; name: string; description: string; url: string; revision: string; last_commit: string; last_sync_at?: number | null; last_sync_status: string; active: boolean; updated_at: number };
export type HostsManagerPowerProfile = { id: string; name: string; provider: "none" | "wol" | "redfish" | "ipmi" | "proxmox"; address: string; mac_address: string; active: boolean; updated_at: number };
export type HostsManagerBackup = { id?: string; filename: string; description?: string; size?: number; checksum?: string; created_at?: number; created_by?: string };
export type DockerPaged<T = Record<string, unknown>> = { items: T[]; total: number; page: number; page_size: number; pages: number };
export type DockerDashboard = { status: ModuleStatus; counts: Record<string, number>; storage: Array<Record<string, unknown>>; security: Array<{ level: string; message: string }>; engine: Record<string, unknown>; usage: { cpu_percent?: number; memory_bytes?: number }; events: Array<Record<string, unknown>>; updates: Array<Record<string, unknown>>; prune_preview: { total?: number; estimated_reclaimable?: number } };
export type DockerContainer = { ID?: string; Names?: string; Image?: string; State?: string; Status?: string; Ports?: string; Size?: string; [key: string]: unknown };
export type DockerContainerSettings = {
  name: string; resource_limits_enabled: boolean; cpu_priority: "low" | "medium" | "high"; memory_mb: number | null;
  auto_restart: boolean; restart_policy: string; portal_enabled: boolean; portal_port: number | null; portal_published_port: number | null;
  portal_protocol: "http" | "https"; compose_managed: boolean;
  available_ports: Array<{ target: number; published: number; protocol: "tcp" | "udp"; host_ip?: string | null }>;
};
export type DockerContainerSettingsUpdate = Pick<DockerContainerSettings, "name" | "resource_limits_enabled" | "cpu_priority" | "memory_mb" | "auto_restart" | "portal_enabled" | "portal_port" | "portal_protocol"> & { confirmation: string };
export type DockerImage = { ID?: string; Repository?: string; Tag?: string; Digest?: string; Size?: string; CreatedSince?: string; consumers?: string[]; [key: string]: unknown };
export type DockerNetworkContainer = { id: string; name: string; endpoint_id?: string; mac_address?: string; ipv4_address?: string; ipv6_address?: string; state?: string; connected?: boolean };
export type DockerNetwork = {
  Name: string; ID?: string; Driver: string; Scope?: string; IPv6?: boolean;
  subnets?: string[]; gateways?: string[]; ip_ranges?: string[];
  container_count?: number; containers?: DockerNetworkContainer[];
  internal?: boolean; attachable?: boolean; system?: boolean;
  options?: Record<string, string>; labels?: Record<string, string>;
  [key: string]: unknown;
};
export type DockerApp = { id: string; name: string; description: string; image: string; container: string; category: string; panel_port: number; ports: string[]; version: string; required_secrets: string[]; architectures: string[]; healthcheck: string; dependencies: string[]; minimum_memory_mb: number; documentation_url: string; update_strategy: string; backup_strategy: string; uninstall_strategy: string; installed: boolean; running: boolean; managed: boolean; status: string };
export type DockerArtifact = { id: string; kind: string; display_name: string; checksum: string; size: number; created_at: number; created_by: string; metadata: Record<string, unknown> };
export type DockerRegistryProvider = "docker_hub" | "ghcr" | "gitlab" | "quay" | "custom";
export type DockerRegistry = { id: string; name: string; provider: DockerRegistryProvider; server: string; username: string; tls: boolean; ca_certificate_configured: boolean; secret_configured: boolean; built_in?: boolean; public_access?: boolean; created_at: number; updated_at: number };
export type DockerRegistrySource = { id: string; name: string; provider: DockerRegistryProvider; server: string; built_in: boolean; public_access: boolean };
export type DockerRegistryCatalogImage = {
  registry_id: string; registry: string; provider: DockerRegistryProvider; repository: string; pull_reference: string;
  description: string; stars: number; official: boolean; automated: boolean | null; [key: string]: unknown;
};
export type DockerRegistryPagination = { page: number; page_size: number; total: number; pages: number; has_next: boolean; truncated: boolean };
export type DockerRegistryCatalogResult = { items: DockerRegistryCatalogImage[]; pagination: DockerRegistryPagination; source: DockerRegistrySource };
export type DockerRegistryTagsResult = { repository: string; pull_reference: string; tags: string[]; pagination: DockerRegistryPagination; source: DockerRegistrySource };
export type DockerPortMapping = { host_ip?: string | null; published: number; target: number; protocol?: "tcp" | "udp" };
export type DockerMount = { type: "volume" | "bind" | "tmpfs"; source?: string; target: string; read_only?: boolean; tmpfs_size_mb?: number | null };
export type DockerUlimit = { name: "nofile" | "nproc"; soft: number; hard: number };
export type DockerResourceLimits = {
  cpus?: number | null; cpu_shares?: number | null; cpuset_cpus?: string | null; cpu_period?: number | null; cpu_quota?: number | null;
  memory_mb?: number | null; memory_swap_mb?: number | null; memory_reservation_mb?: number | null; memory_swappiness?: number | null;
  shm_size_mb?: number | null; pids?: number | null; blkio_weight?: number | null; oom_score_adj?: number | null; oom_kill_disable?: boolean;
  ulimits?: DockerUlimit[];
};
export type DockerHostResources = {
  logical_cpus: number; memory_bytes: number; memory_available_bytes: number; swap_bytes: number; cgroup_version: string; rootless: boolean;
  capabilities: { advanced_cpu: boolean; memory_swappiness: boolean; oom_controls: boolean; blkio_weight: boolean; ulimits: boolean };
};
export type DockerContainerCreate = {
  name: string; image: string; pull_policy?: "missing" | "always" | "never";
  environment?: Record<string, string>; secret_environment?: Record<string, string>;
  ports?: DockerPortMapping[]; mounts?: DockerMount[]; network?: string;
  network_aliases?: string[]; hostname?: string | null; entrypoint?: string | null; working_dir?: string | null; user?: string | null;
  restart_policy?: "no" | "always" | "unless-stopped" | "on-failure";
  limits?: DockerResourceLimits;
  healthcheck?: { type: "none" | "http" | "tcp"; port?: number | null; path?: string; interval_seconds?: number; timeout_seconds?: number; retries?: number; start_period_seconds?: number };
  labels?: Record<string, string>; read_only?: boolean; init?: boolean; auto_start?: boolean; confirmation?: string;
};
export type DockerContainerDefaultsPolicy = {
  resource_limits_enabled: boolean;
  memory_mb: number;
  memory_swap_mb: number;
  cpus: number;
  pids: number;
};
export type DockerContainerAction = {
  action: "start" | "stop" | "restart" | "pause" | "unpause" | "kill" | "rename" | "remove" | "duplicate" | "recreate" | "check_update" | "update";
  timeout?: number; signal?: "KILL" | "TERM" | "HUP" | "INT" | "QUIT" | "USR1" | "USR2";
  force?: boolean; new_name?: string; image?: string | null; confirmation?: string; pam_password?: string | null;
};
export type DockerImageAction = { action: "pull" | "update" | "remove" | "prune" | "save"; image?: string; platform?: "linux/amd64" | "linux/arm64" | "linux/arm/v7"; force?: boolean; confirmation?: string; pam_password?: string | null };
export type DockerComposeSave = { content: string; environment?: Record<string, string>; secret_environment?: Record<string, string> | null; description?: string };
export type DockerComposeAction = { action: "up" | "down" | "start" | "stop" | "restart" | "pull" | "recreate" | "scale" | "delete" | "validate"; services?: string[]; scale?: Record<string, number>; remove_volumes?: boolean; confirmation?: string; pam_password?: string | null };
export type DockerVolumeAction = { action: "remove" | "prune" | "backup" | "restore" | "clone"; target_name?: string | null; backup_id?: string | null; force?: boolean; confirmation?: string; pam_password?: string | null };
export type DockerNetworkAction = { action: "remove" | "prune" | "connect" | "disconnect"; container?: string | null; force?: boolean; confirmation?: string; pam_password?: string | null };
export type DockerEngineAction = { action: "install" | "reinstall" | "update" | "start" | "stop" | "restart" | "enable" | "disable" | "test"; confirmation?: string; pam_password?: string | null };
export type DockerRegistrySave = { name: string; provider: DockerRegistryProvider; server: string; username: string; password?: string | null; tls?: boolean; ca_certificate?: string | null };
export type DockerVolumeCreate = { name: string; labels?: Record<string, string> };
export type DockerNetworkCreate = {
  name: string; driver: "bridge";
  ipv4_mode: "auto" | "manual"; ipv4_subnet: string | null; ipv4_ip_range: string | null; ipv4_gateway: string | null;
  ipv6_mode: "none" | "manual"; ipv6_subnet: string | null; ipv6_ip_range: string | null; ipv6_gateway: string | null;
  internal: boolean; disable_ip_masquerade: boolean; labels: Record<string, string>;
};
export type DockerDefaultBridgeConfig = {
  ipv4_mode: "auto" | "manual"; ipv4_subnet: string | null; ipv4_ip_range: string | null; ipv4_gateway: string | null;
  ipv6_mode: "none" | "manual"; ipv6_subnet: string | null; ipv6_gateway: string | null;
  disable_ip_masquerade: boolean;
};
export type DockerDefaultBridgeSave = DockerDefaultBridgeConfig & { confirmation: string; pam_password: string };
export type DockerPrunePlan = { resources: string[]; items: Array<{ type: string; id?: string; name?: string; size?: string | number | null }>; total: number; estimated_reclaimable: number };
export type DockerAppInstall = { secret_environment?: Record<string, string>; timezone?: string; hostname?: string; panel_port?: number; dns_port?: number; network?: string; confirmation?: string };
export type DockerAppAction = { confirmation?: string; pam_password?: string | null };
export type DockerBackupRestore = { new_name: string; secret_environment?: Record<string, string>; confirmation?: string; pam_password?: string | null };
export type DockerPrune = { resources: Array<"containers" | "images" | "networks" | "volumes" | "build_cache">; confirmation?: string; pam_password?: string | null };
export type PackagePlan = {
  module_id: string;
  action: "install" | "reinstall" | "update" | "uninstall" | "start" | "stop" | "restart" | "reload" | "enable" | "disable" | "apply" | "diagnostics" | "restore" | "firewall" | "manage";
  distribution: { id: string; name: string; version_id: string; architecture: string; package_manager?: string | null };
  compatible: boolean;
  blocked_by_proxmox: boolean;
  packages: string[];
  installation_type?: "system_package" | "command" | "download_package" | "unsupported" | null;
  installation_description?: string;
  services: string[];
  ports: string[];
  config_paths: string[];
  data_paths: string[];
  permissions: string[];
  dependencies: string[];
  conflicts: string[];
  warnings: string[];
  requires_reboot: boolean;
  remove_data: boolean;
  previous_version?: string | null;
  target_version?: string | null;
  steps: string[];
};
export type PackageModule = {
  id: string;
  manifest: PackageManifest;
  state: { installed: boolean; installed_version?: string | null; available_version: string; update_available: boolean; requires_reboot: boolean; needs_configuration?: boolean };
  services: Record<string, string>;
  status: string;
  compatible: boolean;
  compatibility_error?: string | null;
  blocked_by_proxmox: boolean;
  distribution: { id: string; name: string; architecture: string; package_manager?: string | null };
  jobs: AppJob[];
};
export type StoreApp = PackageModule;
export type PackageHistoryItem = { id: number; job_id: string; module_id: string; action: string; status: string; actor: string; created_at: number; finished_at?: number | null; message: string };
export type PackageSource = { id: string; name: string; github_url: string; branch: string; enabled: boolean; created_at: number; updated_at: number; last_sync_at?: number | null; validation_error: string; metadata: Record<string, unknown> };
export type StorePlugin = {
  id: string;
  name: string;
  github_url: string;
  branch: string;
  enabled: boolean;
  codex_instructions: string;
  created_at: number;
  updated_at: number;
};
export type SambaShare = {
  name: string;
  path: string;
  comment: string;
  enabled: boolean;
  browseable: boolean;
  hidden?: boolean;
  read_only: boolean;
  guest_ok: boolean;
  valid_users: string[];
  valid_groups?: string[];
  write_list?: string[];
  read_list?: string[];
  admin_users?: string[];
  force_user?: string | null;
  force_group?: string | null;
  force_create_mode?: string;
  force_directory_mode?: string;
  inherit_permissions?: boolean;
  veto_files?: string;
  recycle_bin?: boolean;
  recycle_versions?: boolean;
  vfs_objects?: string[];
  create_directory?: boolean;
  directory_owner?: string;
  directory_group?: string;
  directory_mode?: string;
  advanced_options?: Record<string, string>;
  create_mask: string;
  directory_mask: string;
  allow_proxmox_storage?: boolean;
};
export type SambaConfig = { shares: SambaShare[]; global_options?: Record<string, string> };
export type SambaValidation = { ok: boolean; stdout: string; stderr: string; exit_code?: number };
export type SambaStatus = {
  installed: boolean;
  managed_config: boolean;
  include_configured: boolean;
  external_config: boolean;
  services: Record<string, string>;
  ports: Record<string, boolean>;
  validation: SambaValidation;
  shares: SambaShare[];
  history: Array<Record<string, unknown>>;
  last_backup?: string | null;
  proxmox_safe_mode: boolean;
};
export type SambaUser = { username: string; uid: number; home: string; shell: string; system: boolean; samba_enabled: boolean };
export type SambaModuleUser = SambaUser & { status: string; groups: string[]; last_changed?: number | null };
export type SambaSession = { id: string; username: string; client: string; ip: string; protocol: string; share: string; open_files: number; connected_at?: number | string | null; pid?: number | null };
export type SambaShareAccess = { share: string; path: string; resolved_path: string; exists: boolean; is_directory: boolean; read_only: boolean; mode: string | null; ok: boolean; warnings: string[]; errors: string[] };
export type NetworkMount = {
  id: string;
  name: string;
  type: "smb" | "nfs" | "sshfs" | "webdav";
  host: string;
  remote: string;
  mount_point: string;
  owner: string;
  read_only: boolean;
  persistent: boolean;
  status: "mounted" | "unmounted" | "error" | "testing" | "mounting" | "unmounting" | "remounting" | "missing_packages" | "host_unavailable" | "migration_required" | "migrating" | "manual_intervention_required";
  actual_mounted: boolean;
  last_error: string;
  last_operation: string;
  last_operation_at: number | null;
  missing_packages: string[];
  migration_status: "ready" | "required" | "migrating" | "failed";
  manual_intervention: boolean;
  allowed_users: string[];
  allowed_groups: string[];
  config: Record<string, unknown> & { has_secret?: boolean; automount?: boolean };
  fs: { total: number; used: number; free: number; fs_type: string } | null;
  jobs: Array<{ id: string; action: string; status: string; created_at?: number; finished_at?: number | null; exit_code: number | null; error: string; log_tail: string[] }>;
};
export type NetworkMountPayload = {
  name: string;
  type: NetworkMount["type"];
  host: string;
  share?: string;
  export_path?: string;
  remote_path?: string;
  username?: string;
  password?: string;
  domain?: string;
  smb_version?: string;
  nfs_version?: string;
  ssh_port?: number;
  ssh_auth?: "key" | "password";
  read_only?: boolean;
  persistent?: boolean;
  automount?: boolean;
  uid?: string;
  gid?: string;
  file_mode?: string;
  dir_mode?: string;
  noexec?: boolean;
  advanced_options?: string[];
  allowed_users?: string[];
  allowed_groups?: string[];
  force_empty_mountpoint?: boolean;
  remove_secret?: boolean;
};
export type NetworkMountRoot = {
  id: string;
  name: string;
  mount_point: string;
  read_only: boolean;
  status: "mounted";
  filesystem: { total: number; used: number; free: number; fs_type: string } | null;
};
export type LocalDisk = {
  device: string;
  mount_point: string;
  name: string;
  fs_type: string;
  read_only: boolean;
  removable: boolean;
  total: number;
  used: number;
  free: number;
};
export type MountActionResult = {
  job?: { id: string; mount_id: string; action: string; status: string; exit_code: number | null; error: string; log_tail: string[] };
  dry_run?: boolean;
  dependencies?: string[];
  command?: string[];
};
export type ProxmoxSafety = {
  is_proxmox: boolean;
  safe_mode_enabled: boolean;
  protected_paths: string[];
  blocked_admin_features: string[];
  allowed_roots_effective: string[];
  service_user: string;
  warnings: string[];
};
export type NetworkInterfaceAddress = {
  family: "ipv4" | "ipv6";
  address: string;
  prefix_length: number;
  scope: string;
};
export type NetworkInterfaceDetail = {
  name: string;
  state: "up" | "down" | "dormant" | "lowerlayerdown" | "unknown";
  carrier: boolean | null;
  speed_mbps: number | null;
  duplex: "full" | "half" | null;
  mtu: number | null;
  mac_address: string | null;
  addresses: NetworkInterfaceAddress[];
  rx_bytes: number;
  rx_packets: number;
  rx_errors: number;
  rx_dropped: number;
  tx_bytes: number;
  tx_packets: number;
  tx_errors: number;
  tx_dropped: number;
  rx_bytes_per_sec: number | null;
  tx_bytes_per_sec: number | null;
  system: boolean;
};
export type NetworkOverview = {
  timestamp: number;
  sample_interval_seconds: number | null;
  interfaces: NetworkInterfaceDetail[];
  warnings: string[];
};
export type DnsConfiguration = {
  resolv_conf: {
    path: string;
    symlink_target: string | null;
    mode: "stub" | "uplink" | "static";
    nameservers: string[];
    search: string[];
    options: string[];
  };
  systemd_resolved: {
    available: boolean;
    global_servers: string[];
    global_domains?: string[];
    links: Array<{ interface: string; servers: string[]; domains: string[] }>;
  };
  warnings: string[];
};
export type DnsTestResult = {
  hostname: string;
  success: boolean;
  addresses: string[];
  servers: Array<{
    server: string;
    success: boolean;
    rcode: string | null;
    addresses: string[];
    latency_ms: number | null;
    error: string | null;
  }>;
  tested_at: number;
};
export type NetworkRoute = {
  family: "ipv4" | "ipv6";
  destination: string;
  gateway: string | null;
  device: string | null;
  preferred_source: string | null;
  protocol: string | null;
  scope: string | null;
  type: string;
  table: string;
  metric: number | null;
  nexthops: Array<{ gateway: string | null; device: string | null; weight: number | null }>;
};
export type NetworkRule = {
  family: "ipv4" | "ipv6";
  priority: number | null;
  from: string;
  to: string;
  table: string | null;
  fwmark: string | null;
  input_interface: string | null;
  output_interface: string | null;
  action: string;
};
export type RoutingSnapshot = {
  timestamp: number;
  routes: NetworkRoute[];
  rules: NetworkRule[];
  gateways: Array<{ family: "ipv4" | "ipv6"; address: string; device: string | null; metric: number | null; table: string }>;
  warnings: string[];
  read_only: true;
};
export type NetworkIPConfiguration = {
  method: "disabled" | "dhcp" | "slaac" | "dhcpv6" | "manual";
  addresses: Array<{ address: string; prefix: number }>;
  gateway?: string | null;
  metric: number;
  default_route: boolean;
  ignore_auto_routes: boolean;
  ignore_auto_dns: boolean;
  dns: string[];
  search_domains: string[];
  privacy_extensions: boolean;
};
export type NetworkInterfaceConfiguration = {
  name: string;
  kind: "physical" | "bond" | "vlan" | "bridge";
  autostart: boolean;
  mtu: number;
  parent?: string | null;
  vlan_id?: number | null;
  members: string[];
  bond_mode: "active-backup" | "balance-rr" | "balance-xor" | "broadcast" | "802.3ad" | "balance-tlb" | "balance-alb";
  primary?: string | null;
  miimon: number;
  updelay: number;
  downdelay: number;
  lacp_rate: "slow" | "fast";
  xmit_hash_policy: "layer2" | "layer2+3" | "layer3+4";
  stp: boolean;
  forward_delay: number;
  ipv4: NetworkIPConfiguration;
  ipv6: NetworkIPConfiguration;
};
export type NetworkDnsSettings = {
  automatic: boolean;
  servers: string[];
  search_domains: string[];
  routing_domains: string[];
  per_interface: Record<string, string[]>;
  priority: number;
  ignore_dhcp: boolean;
};
export type ManagedNetworkRoute = {
  id?: string;
  name: string;
  family: "ipv4" | "ipv6";
  destination: string;
  route_type: "unicast" | "blackhole" | "unreachable" | "prohibit";
  gateway?: string | null;
  interface?: string | null;
  metric: number;
  table: number;
  source?: string | null;
  autostart: boolean;
  enabled: boolean;
};
export type NetworkTrafficRule = {
  id?: string;
  name: string;
  interface: string;
  direction: "egress" | "ingress";
  guaranteed_kbit: number;
  maximum_kbit: number;
  priority: number;
  protocol: "any" | "tcp" | "udp";
  source_cidr?: string | null;
  destination_cidr?: string | null;
  source_port?: number | null;
  destination_port?: number | null;
  enabled: boolean;
};
export type NetworkChange =
  | { operation: "save_interface"; interface: NetworkInterfaceConfiguration }
  | { operation: "delete_interface"; interface_name: string }
  | { operation: "set_link"; interface_name: string; link_up: boolean }
  | { operation: "save_dns"; dns: NetworkDnsSettings }
  | { operation: "save_route"; route: ManagedNetworkRoute }
  | { operation: "delete_route"; object_id: string }
  | { operation: "save_traffic"; traffic: NetworkTrafficRule }
  | { operation: "delete_traffic"; object_id: string };
export type NetworkPlan = {
  id: string; provider: string; target: string; before: Record<string, unknown>; after: Record<string, unknown>;
  commands: string[][]; warnings: string[]; high_risk: boolean; required_phrase: string;
  rollback_supported: boolean; rollback_seconds: number; client_interface: string | null;
  previous_panel_address?: string | null; predicted_panel_address?: string | null; reachable_addresses?: string[];
  confirmation_timeout_seconds: number; rollback_method: string; automatic_rollback_without_confirmation: boolean;
};
export type NetworkPolicy = {
  change_confirmation_timeout_seconds: number;
  minimum_seconds: number;
  maximum_seconds: number;
  default_seconds: number;
};
export type ShutdownPolicy = { detailed_information: boolean };
export type NetworkTransaction = {
  id: string; transaction_id?: string; provider: string;
  state: "pending_confirmation" | "rollback_started" | "confirmed" | "rolled_back" | "failed";
  status?: "pending_confirmation" | "rollback_pending" | "rollback_started" | "confirmed" | "rolled_back" | "failed";
  confirmed?: boolean; rollback_pending?: boolean; rollback_started?: boolean; rolled_back?: boolean; failed?: boolean;
  started_at: number; deadline: number; rollback_unit: string | null; target: string;
  created_at?: number; deadline_at?: number; remaining_seconds?: number; current_server_time?: number;
  server_time?: number; confirmation_timeout_seconds?: number;
  previous_panel_address?: string | null; predicted_panel_address?: string | null; reachable_addresses?: string[];
};
export type NetworkManagementState = {
  provider: { id: string; writable: boolean; capabilities: Record<string, boolean>; warnings: string[] };
  hostname: string;
  interfaces: NetworkInterfaceDetail[];
  dns: DnsConfiguration;
  routing: RoutingSnapshot;
  managed: {
    interfaces: Record<string, NetworkInterfaceConfiguration>;
    dns: NetworkDnsSettings | null;
    routes: Record<string, ManagedNetworkRoute>;
    traffic: Record<string, NetworkTrafficRule>;
  };
  transaction: NetworkTransaction | null;
  tools: Record<string, boolean>;
};
export type NetworkConnectivityResult = {
  kind: "ping" | "trace" | "tcp"; target: string; port: number | null; success: boolean; duration_ms: number; output: string;
};
export type HealthStatus = {
  status: "ok";
  service: string;
  deployment_phase?: "switching" | "draining" | null;
  update_id?: string | null;
};
