import { Play, RefreshCw, RotateCcw, Stethoscope } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { api, type ModuleBackup, type ModuleDiagnostic, type ModuleJob, type ModuleStatus, type ModuleSummary } from "../../api";
import type { ToastFn, Translate } from "../../app/types";
import { AdminActionDialog } from "../admin/AdminActionDialog";
import { PackageJobDialog } from "../package-center/PackageJobDialog";
import { ModuleAppShell, ModuleHealthCard, translateServiceState, type ModuleSection } from "./common/ModuleAppShell";
import { ModuleBackups, ModuleDangerZone, ModuleDiagnostics, ModuleJobProgress, ModuleLogs, ModuleServiceControls } from "./common/ModuleComponents";
import { ModuleUninstallDialog } from "./common/ModuleUninstallDialog";
import { SambaModuleApp } from "./samba/SambaModuleApp";
import { ManagedModuleApp } from "./ManagedModuleApp";
import { DockerManagerApp } from "../docker/DockerManagerApp";
import { AnsibleControllerApp } from "./ansible/AnsibleControllerApp";
import { HostsManagerApp } from "./hosts/HostsManagerApp";

const emptyStatus: ModuleStatus = { installed: false, update_available: false, service_state: "unknown", service_enabled: false, services: {}, health: "unknown", health_message: "", last_action: "", last_action_status: "", last_error: "", metrics: {} };

export function ModuleApp({ moduleId, initialPath, draftKey, permissions = [], t, toast, onOpenFolder, onDirtyChange }: { moduleId: string; initialPath?: string; draftKey?: string; permissions?: string[]; t: Translate; toast: ToastFn; onOpenFolder: (path: string) => void; onDirtyChange: (dirty: boolean) => void }) {
  if (moduleId === "samba") return <SambaModuleApp initialSharePath={initialPath} readOnly={!permissions.includes("modules.configure")} canReinstall={permissions.includes("modules.update")} t={t} toast={toast} onOpenFolder={onOpenFolder} onDirtyChange={onDirtyChange} />;
  if (moduleId === "docker") return <DockerManagerApp draftKey={draftKey} permissions={permissions} t={t} toast={toast} onDirtyChange={onDirtyChange} />;
  if (moduleId === "ansible-controller") return <AnsibleControllerApp permissions={permissions} t={t} toast={toast} />;
  if (moduleId === "hosts-manager") return <HostsManagerApp permissions={permissions} t={t} toast={toast} />;
  if (["linux-updates", "pihole", "adguard-home", "postgresql", "mariadb", "redis", "home-assistant"].includes(moduleId)) return <ManagedModuleApp moduleId={moduleId} permissions={permissions} t={t} toast={toast} />;
  return <GenericModuleApp moduleId={moduleId} t={t} toast={toast} />;
}

function GenericModuleApp({ moduleId, t, toast }: { moduleId: string; t: Translate; toast: ToastFn }) {
  const [summary, setSummary] = useState<ModuleSummary | null>(null); const [status, setStatus] = useState(emptyStatus); const [section, setSection] = useState<ModuleSection>("overview"); const [job, setJob] = useState<ModuleJob | null>(null); const [liveJob, setLiveJob] = useState<ModuleJob | null>(null); const [diagnostics, setDiagnostics] = useState<ModuleDiagnostic[]>([]); const [backups, setBackups] = useState<ModuleBackup[]>([]); const [uninstallOpen, setUninstallOpen] = useState(false); const [dialog, setDialog] = useState<{ type: "service"; action: "start" | "stop" | "restart" | "reload" | "enable" | "disable" } | { type: "diagnostics" } | { type: "backup" } | { type: "restore" | "delete"; backup: ModuleBackup } | null>(null);
  const refresh = useCallback(async () => { try { const data = await api.module(moduleId); setSummary(data); setStatus(data.module_status); setJob(data.active_job || null); } catch (error) { toast(error instanceof Error ? error.message : t("error.generic"), "error", "admin"); } }, [moduleId, t, toast]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => { if (!document.hidden) void refresh(); }, 5000); return () => window.clearInterval(timer); }, [refresh]);
  useEffect(() => { if (section === "diagnostics") void api.moduleDiagnostics(moduleId).then((data) => setDiagnostics(data.diagnostics)); if (section === "backups") void api.moduleBackups(moduleId).then(setBackups); }, [moduleId, section]);
  function trackJob(next: ModuleJob) { setJob(next); setLiveJob(next); }
  async function submit(values: Record<string, string>) { if (!dialog) return; if (dialog.type === "service") trackJob((await api.moduleService(moduleId, dialog.action)).job); else if (dialog.type === "diagnostics") trackJob((await api.runModuleDiagnostics(moduleId)).job); else if (dialog.type === "backup") { await api.createModuleBackup(moduleId, values.description); setBackups(await api.moduleBackups(moduleId)); } else if (dialog.type === "restore") trackJob((await api.restoreModuleBackup(moduleId, dialog.backup.id)).job); else if (dialog.type === "delete") { await api.deleteModuleBackup(moduleId, dialog.backup.id); setBackups(await api.moduleBackups(moduleId)); } toast(t("admin.actionCompleted"), "ok", "admin"); }
  if (!summary) return <div className="loading-state">{t("status.loading")}</div>;
  const sections: ModuleSection[] = ["overview", "service", ...(summary.capabilities.logs ? ["logs" as const] : []), ...(summary.capabilities.diagnostics ? ["diagnostics" as const] : []), ...(summary.capabilities.backups ? ["backups" as const] : []), "info"];
  let content: React.ReactNode;
  if (section === "overview") content = <><div className="module-health-grid"><ModuleHealthCard title={t("module.packageState")} value={status.installed ? t("common.enabled") : t("common.disabled")} /><ModuleHealthCard title={t("module.version")} value={status.package_version || "—"} /><ModuleHealthCard title={t("module.serviceState")} value={translateServiceState(status.service_state, t)} /><ModuleHealthCard title={t("module.health")} value={t(`module.health.${status.health}`)} /></div>{job && <ModuleJobProgress job={job} t={t} />}</>;
  else if (section === "service") content = <><ModuleServiceControls status={status} disabled={Boolean(job)} t={t} onAction={(action) => setDialog({ type: "service", action })} /><div className="module-service-list">{Object.entries(status.services).map(([name, value]) => <article key={name}><strong>{name}</strong><span>{value.state}</span><span>{value.enabled ? t("module.enabledAtBoot") : t("module.disabledAtBoot")}</span></article>)}</div></>;
  else if (section === "logs") content = <ModuleLogs moduleId={moduleId} t={t} toast={toast} />;
  else if (section === "diagnostics") content = <><div className="module-section-toolbar"><button onClick={() => setDialog({ type: "diagnostics" })}><Stethoscope />{t("module.runDiagnostics")}</button></div><ModuleDiagnostics diagnostics={diagnostics} t={t} /></>;
  else if (section === "backups") content = <ModuleBackups backups={backups} t={t} onCreate={() => setDialog({ type: "backup" })} onRestore={(backup) => setDialog({ type: "restore", backup })} onDelete={(backup) => setDialog({ type: "delete", backup })} />;
  else content = <><section className="module-info"><dl><dt>{t("module.version")}</dt><dd>{summary.manifest.version}</dd><dt>{t("module.homepage")}</dt><dd>{summary.manifest.homepage || "—"}</dd><dt>{t("module.license")}</dt><dd>{summary.manifest.license}</dd><dt>{t("module.category")}</dt><dd>{summary.manifest.category}</dd></dl></section><ModuleDangerZone name={summary.manifest.name} t={t} onUninstall={() => setUninstallOpen(true)} /></>;
  return <><ModuleAppShell name={summary.manifest.name} status={status} activeJob={job ? { operation: job.operation || job.action, progress: job.progress } : null} section={section} sections={sections} t={t} onSection={setSection} actions={<><button onClick={() => setDialog({ type: "service", action: "start" })}><Play />{t("module.start")}</button><button onClick={() => setDialog({ type: "service", action: "restart" })}><RotateCcw />{t("module.restart")}</button><button onClick={() => void refresh()}><RefreshCw />{t("action.refresh")}</button></>}>{content}</ModuleAppShell>{uninstallOpen && <ModuleUninstallDialog item={summary} t={t} toast={toast} onClose={() => setUninstallOpen(false)} onStarted={(started) => { trackJob(started); void refresh(); }} />}{liveJob && <PackageJobDialog initialJob={liveJob} moduleName={summary.manifest.name} t={t} onClose={() => setLiveJob(null)} />}{dialog && <AdminActionDialog title={dialog.type === "service" ? t(`module.${dialog.action}`) : dialog.type === "diagnostics" ? t("module.runDiagnostics") : dialog.type === "backup" ? t("module.createBackup") : dialog.type === "restore" ? t("module.restore") : t("module.deleteBackup")} fields={dialog.type === "backup" ? [{ name: "description", label: t("module.backupDescription") }] : []} danger={["restore", "delete"].includes(dialog.type)} t={t} onClose={() => setDialog(null)} onSubmit={submit} />}</>;
}
