import { useState } from "react";
import type { ModuleValidationResult } from "../../../api";
import type { Translate } from "../../../app/types";
import { Modal } from "../../../components/Modal";

export function ModuleApplyPlanDialog({ validation, t, onClose, onApply }: { validation: ModuleValidationResult; t: Translate; onClose: () => void; onApply: (confirmations: string[]) => Promise<void> }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [confirmations, setConfirmations] = useState<Set<string>>(new Set());
  const allConfirmed = validation.confirmations_required.every((item) => confirmations.has(item));
  async function apply() { setSaving(true); setError(""); try { await onApply([...confirmations]); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("error.generic")); } finally { setSaving(false); } }
  return <Modal wide title={t("module.changePlan")} closeLabel={t("action.close")} onClose={onClose} footer={<><button type="button" onClick={onClose}>{t("action.cancel")}</button><button className="button-primary" type="button" disabled={saving || !validation.ok || !allConfirmed} onClick={() => void apply()}>{saving ? t("status.loading") : t("module.applyConfiguration")}</button></>}><div className="module-apply-plan"><section><h3>{t("module.changes")}</h3>{validation.changes.length ? <ul>{validation.changes.map((change, index) => <li key={`${change.kind}-${change.name}-${index}`}><strong>{t(`module.change.${change.kind}`)}</strong><span>{change.name}</span>{change.before !== undefined && <small>{String(change.before || "—")} → {String(change.after || "—")}</small>}</li>)}</ul> : <p>{t("module.noChanges")}</p>}</section>{validation.warnings.length > 0 && <section className="warnings"><h3>{t("module.warnings")}</h3><ul>{validation.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></section>}{validation.confirmations_required.map((item) => <label className="module-security-confirmation" key={item}><input type="checkbox" checked={confirmations.has(item)} onChange={(event) => setConfirmations((current) => { const next = new Set(current); if (event.target.checked) next.add(item); else next.delete(item); return next; })} /><span><strong>{t(`module.confirm.${item}`)}</strong><small>{t(`module.confirm.${item}Hint`)}</small></span></label>)}{validation.errors.length > 0 && <section className="errors"><h3>{t("module.errors")}</h3><ul>{validation.errors.map((item) => <li key={item}>{item}</li>)}</ul></section>}<section><h3>{t("module.validationResult")}</h3><pre>{validation.validator_output || t("module.validationPassed")}</pre></section>{error && <p className="error-state compact-error">{error}</p>}</div></Modal>;
}
