import { enrollmentScript, request } from "../../../core/api/transport";
import type { HostsManagerApmid, HostsManagerBackup, HostsManagerCapability, HostsManagerCredential, HostsManagerDashboard, HostsManagerEnrollmentInput, HostsManagerEnrollmentToken, HostsManagerEnvironment, HostsManagerGroup, HostsManagerHost, HostsManagerHostnamePattern, HostsManagerOperation, HostsManagerPowerProfile, HostsManagerRepository, HostsManagerSettings, HostsManagerSettingsUpdate } from "../../../core/api/contracts";

export const hostsManagerClient = {
  hostsManagerDashboard: () => request<HostsManagerDashboard>("/api/modules/hosts-manager/dashboard"),
  hostsManagerSettings: () => request<HostsManagerSettings>("/api/modules/hosts-manager/settings"),
  saveHostsManagerSettings: (payload: HostsManagerSettingsUpdate) => request<HostsManagerSettings>("/api/modules/hosts-manager/settings", { method: "PUT", body: JSON.stringify(payload) }),
  hostsManagerEnvironments: () => request<HostsManagerEnvironment[]>("/api/modules/hosts-manager/environments"),
  saveHostsManagerEnvironment: (payload: Record<string, unknown>, id = "") => request<HostsManagerEnvironment>(id ? `/api/modules/hosts-manager/environments/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/environments", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerEnvironment: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/environments/${encodeURIComponent(id)}`, { method: "DELETE" }),
  hostsManagerApmids: () => request<HostsManagerApmid[]>("/api/modules/hosts-manager/apmids"),
  saveHostsManagerApmid: (payload: { code: string; description: string; active: boolean }, id = "") => request<HostsManagerApmid>(id ? `/api/modules/hosts-manager/apmids/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/apmids", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerApmid: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/apmids/${encodeURIComponent(id)}`, { method: "DELETE" }),
  syncHostsManagerApmidGroups: () => request<{ created: number; updated: number; total: number }>("/api/modules/hosts-manager/apmids/sync-groups", { method: "POST", body: "{}" }),
  hostsManagerHostnamePatterns: () => request<HostsManagerHostnamePattern[]>("/api/modules/hosts-manager/hostname-patterns"),
  saveHostsManagerHostnamePattern: (payload: Record<string, unknown>, id = "") => request<HostsManagerHostnamePattern>(id ? `/api/modules/hosts-manager/hostname-patterns/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/hostname-patterns", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerHostnamePattern: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/hostname-patterns/${encodeURIComponent(id)}`, { method: "DELETE" }),
  skipHostsManagerHostnamePattern: (id: string, count = 1, reason = "") => request<{ skipped: string[]; pattern: HostsManagerHostnamePattern }>(`/api/modules/hosts-manager/hostname-patterns/${encodeURIComponent(id)}/skip`, { method: "POST", body: JSON.stringify({ count, reason }) }),
  probeHostsManagerSshOnboarding: (payload: Record<string, unknown>) => request<Record<string, unknown> & { keys?: Array<{ key_type: string; public_key: string; fingerprint: string }>; accepted_key?: { key_type: string; public_key: string; fingerprint: string }; login_available?: boolean; requires_fingerprint_confirmation?: boolean }>("/api/modules/hosts-manager/onboarding/ssh/probe", { method: "POST", body: JSON.stringify(payload) }),
  installHostsManagerAgentOverSsh: (payload: Record<string, unknown>) => request<{ status: string; host: HostsManagerHost; log: string; operation_id: string }>("/api/modules/hosts-manager/onboarding/ssh/install", { method: "POST", body: JSON.stringify(payload) }),
  hostsManagerHosts: (query = "") => request<HostsManagerHost[]>(`/api/modules/hosts-manager/hosts${query ? `?${query}` : ""}`),
  hostsManagerHost: (id: string) => request<HostsManagerHost>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}`),
  saveHostsManagerHost: (payload: Record<string, unknown>, id = "") => request<HostsManagerHost>(id ? `/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/hosts", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerHost: (id: string, name: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}`, { method: "DELETE", body: JSON.stringify({ confirm: true, confirmation_text: name }) }),
  approveHostsManagerHost: (id: string) => request<HostsManagerHost>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/approve`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  disableHostsManagerHost: (id: string) => request<HostsManagerHost>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/disable`, { method: "POST", body: JSON.stringify({ confirm: true }) }),
  hostsManagerAgentHistory: (id: string) => request<{ identities: Array<Record<string, unknown>>; reports: Array<Record<string, unknown>>; versions: Array<Record<string, unknown>>; operations: HostsManagerOperation[] }>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/agent/history`),
  regenerateHostsManagerAgentIdentity: (id: string) => request<{ agent_id: string; host_id: string; token: string; identity_hash: string }>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/agent/identity/regenerate`, { method: "POST", body: JSON.stringify({ confirm: true, confirmation_text: "" }) }),
  invalidateHostsManagerAgentIdentity: (id: string) => request<{ ok: boolean; pairing_required: boolean }>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/agent/identity/invalidate`, { method: "POST", body: JSON.stringify({ confirm: true, confirmation_text: "" }) }),
  hostsManagerGroups: () => request<HostsManagerGroup[]>("/api/modules/hosts-manager/groups"),
  saveHostsManagerGroup: (payload: Record<string, unknown>, id = "") => request<HostsManagerGroup>(id ? `/api/modules/hosts-manager/groups/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/groups", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerGroup: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/groups/${encodeURIComponent(id)}`, { method: "DELETE" }),
  hostsManagerCredentials: () => request<HostsManagerCredential[]>("/api/modules/hosts-manager/credentials"),
  createHostsManagerEnrollmentToken: (payload: HostsManagerEnrollmentInput) => request<HostsManagerEnrollmentToken>("/api/modules/hosts-manager/enrollment-tokens", { method: "POST", body: JSON.stringify(payload) }),
  hostsManagerEnrollmentTokens: () => request<HostsManagerEnrollmentToken[]>("/api/modules/hosts-manager/enrollment-tokens"),
  revokeHostsManagerEnrollmentToken: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/enrollment-tokens/${encodeURIComponent(id)}`, { method: "DELETE" }),
  downloadHostsManagerEnrollmentScript: (url: string, token: string) => enrollmentScript(url, token),
  hostsManagerCapabilities: (id: string) => request<HostsManagerCapability[]>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/capabilities`),
  hostsManagerActionPlan: (id: string, capability: string, parameters: Record<string, unknown> = {}) => request<Record<string, unknown>>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/actions/${encodeURIComponent(capability)}/plan`, { method: "POST", body: JSON.stringify({ parameters, confirm: false, confirmation_text: "" }) }),
  executeHostsManagerAction: (id: string, capability: string, parameters: Record<string, unknown> = {}, confirmationText = "") => request<Record<string, unknown>>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/actions/${encodeURIComponent(capability)}/execute`, { method: "POST", body: JSON.stringify({ parameters, confirm: true, confirmation_text: confirmationText }) }),
  hostsManagerOperations: () => request<HostsManagerOperation[]>("/api/modules/hosts-manager/operations"),
  hostsManagerOperation: (id: string) => request<HostsManagerOperation>(`/api/modules/hosts-manager/operations/${encodeURIComponent(id)}`),
  hostsManagerRepositories: () => request<HostsManagerRepository[]>("/api/modules/hosts-manager/repositories"),
  saveHostsManagerRepository: (payload: Record<string, unknown>, id = "") => request<Record<string, unknown>>(id ? `/api/modules/hosts-manager/repositories/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/repositories", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  syncHostsManagerRepository: (id: string) => request<Record<string, unknown>>(`/api/modules/hosts-manager/repositories/${encodeURIComponent(id)}/sync`, { method: "POST", body: JSON.stringify({ confirm: true, confirmation_text: "" }) }),
  hostsManagerPowerProfiles: () => request<HostsManagerPowerProfile[]>("/api/modules/hosts-manager/power-profiles"),
  saveHostsManagerPowerProfile: (payload: Record<string, unknown>, id = "") => request<Record<string, unknown>>(id ? `/api/modules/hosts-manager/power-profiles/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/power-profiles", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  hostsManagerPowerPlan: (id: string, action: string) => request<Record<string, unknown>>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/power/plan`, { method: "POST", body: JSON.stringify({ action, confirm: false, confirmation_text: "" }) }),
  executeHostsManagerPower: (id: string, action: string, confirmationText = "") => request<Record<string, unknown>>(`/api/modules/hosts-manager/hosts/${encodeURIComponent(id)}/power/execute`, { method: "POST", body: JSON.stringify({ action, confirm: true, confirmation_text: confirmationText }) }),
  startHostsManagerScan: (payload: Record<string, unknown>) => request<Record<string, unknown>>("/api/modules/hosts-manager/scans", { method: "POST", body: JSON.stringify(payload) }),
  validateHostsManagerInventory: (content: string, format = "yaml") => request<Record<string, unknown>>("/api/modules/hosts-manager/inventory/validate", { method: "POST", body: JSON.stringify({ content, format, confirm: false }) }),
  importHostsManagerInventory: (content: string, format = "yaml") => request<Record<string, unknown>>("/api/modules/hosts-manager/inventory/import", { method: "POST", body: JSON.stringify({ content, format, confirm: true }) }),
  saveHostsManagerCredential: (payload: Record<string, unknown>, id = "") => request<HostsManagerCredential>(id ? `/api/modules/hosts-manager/credentials/${encodeURIComponent(id)}` : "/api/modules/hosts-manager/credentials", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }),
  deleteHostsManagerCredential: (id: string) => request<{ ok: boolean }>(`/api/modules/hosts-manager/credentials/${encodeURIComponent(id)}`, { method: "DELETE" }),
  hostsManagerDiagnostics: () => request<{ schema_version: number; checks: Array<{ id: string; status: string; message: string }> }>("/api/modules/hosts-manager/diagnostics"),
  hostsManagerBackups: () => request<HostsManagerBackup[]>("/api/modules/hosts-manager/backups"),
  createHostsManagerBackup: (description = "") => request<Record<string, unknown>>("/api/modules/hosts-manager/backups", { method: "POST", body: JSON.stringify({ description, include_credentials: false, include_repositories: false, confirm: true }) })
} as const;
